### ISSUE TITLE
CacheCow.Client gets thread deadlock when serializing/deserialzing

### ISSUE THREAD

**Issue by aliostad** [aliostad/CacheCow#103]

**Comment by hongymagic** [comment]
Are you able to provide a bit more background on this issue?

I am currently consuming version __0.6.3__ and it seems to be hanging on every subsequent request. Upon profiling, I've found a lot of calls from `InMemoryCacheStore.TryGetValue` to `HttpContentMessageExtensions.ReadAsHttpResponseMessageAsync`. I'm wondering if I've hit the same bug as you.

I'll continue to profile, but right now this is _still_ a problem.

**Comment by aliostad** [comment]
Hi,

I believe I fixed this in 6.3 but are you saying you see it now in 0.6.3? Is it possible to create a minimal repro? What storage are you using?

**Comment by aliostad** [comment]
This is now fixed with 0.6.4.
