### ISSUE TITLE
Invalidate multiple cache entries for the same resource.

### ISSUE THREAD

**Issue by benfoster** [aliostad/CacheCow#105]
In the previous version of our API you could GET a Project resource by slug using a query parameter on the Projects collection e.g.

`/api/projects?slug={slug}`

We now require our "Project Detail" representation includes additional information and this should apply to both "GET by ID" and "GET by Slug".

Since a slug is unique, we introduced the following endpoint in our API:

`/api/projects/byslug/{slug}`

This would return the same Project representation as:

`/api/projects/{id}`

The issue we now have is that updates to projects (done using the ID) is not invalidating the cache entries for the "by slug" endpoint. 

We need to ensure that 

`PUT /api/projects/1`

would clear the cache entry for:

```
/api/projects/1
/api/projects/byslug/{project1Slug}
```

Obviously this is difficult without hitting the database within our LinkedRouteProvider to determine what the slug is for a specific project.

One solution I've considered is to set the location header on GetBySlug responses to the project's permanent URI (by id). This way I can ensure that the same RoutePattern is used.

Does this make sense or would you suggest anything different?

**Comment by aliostad** [comment]
You can implement your own `IRoutePatternProvider` and in `GetLinkedRoutePatterns` provide Linked routes.

**Comment by aliostad** [comment]
Is this OK? Did you get your response?

**Comment by benfoster** [comment]
I'll come back to you tomorrow with some feedback.

Thanks
