### ISSUE TITLE
Multi-tenancy and named-resource route patterns

### ISSUE THREAD

**Issue by benfoster** [aliostad/CacheCow#106]
I've just upgraded to the latest version of CacheCow and have encountered a few issues with our routing configuration.

**Multi-tenant Route Parameters**

Our API is multi-tenant where each tenant (in our case Site) is identified by a `siteId` parameter in our URI templates e.g. `/sites/1/projects/2`.

This is not a problem for most of our routes that follow the standard item/collection conventions but in a few cases we have *named* item resources e.g. `/sites/1/settings` (the settings for site 1). For these resources CacheCow will generate the following Route Pattern:

`/sites/+/settings`

This is a problem as it means that if one tenant (site) updates their settings, the cache entries for all sites will be invalidated.

Some means of *excluding* a parameter from pattern replacement would be useful, otherwise we have to provide our own implementation of [BuildPattern](https://github.com/aliostad/CacheCow/blob/master/src/CacheCow.Server/RoutePatternPolicy/ConventionalRoutePatternProvider.cs#L163).

**Named Resource Route Patterns**

We have a number of *named* resources. The current patterns generated are as below (some could be fixed by excluding the siteId as explained above):

```
Portfolio Tree > /sites/{siteId}/portfolios/tree > /sites/+/portfolios/tree
Blog Tags > /sites/{siteId}/blog/tags > /sites/+/blog/tags
Theme Configurations > /sites/{siteId}/themes/{themeId}/configuration > /sites/{siteId}/themes/+/configuration
```

For the Theme Configurations routes it means that updating the config for one theme clears the cache of configs for all themes. I'm not sure how we could do it but we need a way to mark a route as a "Named Resource" so that the route pattern generated is actually the absolute path itself i.e. `/sites/1/themes/10/configuration`.

**Comment by aliostad** [comment]
Hi Ben,

There is no way CacheCow out of the box can support your routes. It only supports conventional /collection/item and mainly flat structures.

So I am afraid you have to implement your own `IRoutePatternProvider`.

**Comment by aliostad** [comment]
Sorry need to close this.
