### ISSUE TITLE
Routes with changed payload return 304

### ISSUE THREAD

**Issue by Seebiscuit** [aliostad/CacheCow#107]
I'm unclear how CacheCow tracks last modified dates. Most of WebApi routes return either objects or an array (IQueryables, IEnumerables, Lists, Arrays) of objects. It seems that all my GETs, even if the information has since changed, return with a 304 status. I'm using WebApi without any special configurations. 

What is CacheCow looking for to identify whether the payload has in fact changed?

----

**Update**: I read one of Aliostad's articles (http://byterot.blogspot.com/2012/06/aspnet-web-api-caching-handler.html) that gives a rough overview of how CacheCow works. So, I get that a `PUT` or `POST` to some route, say, `/api/cars/id1` will result in a modified timestamp for a `GET` to `/api/cars/id1`. But what often happens is that  I will do a 'PUT' to say, `/api/costs/` and I that ends up changing the model returned on `/api/cars/id1`. How do I tell the cache store that `/api/cars/id1` has been modified?

----

**Update**: I am now using attributes to better manage cache invalidation. However, I'm not getting the desired results. As I explain in my previous **Update** several controllers may be making changes to one model, therefore one route `PUT`/`POST` may be making data in the client from another route stale on a subsequent `GET`. I am trying different combinations of attribute parameters to ensure that some routes do not get cached at all and none seem to have worked. I'm especially stumped that setting `mustRevalidate = false`  on a controller still returns cached data with a status of 304. How do I avoid caching and returning 304 for a controller using the `HttpCacheControlPolicyAttribute`?

**Comment by aliostad** [comment]
As I mentioned in another article, you need to implement your own `IRoutePatternProvider` and in `IRoutePatternProvider` provide Linked routes.
