### ISSUE TITLE
`HttpCacheRefreshPolicy` Not deleting route

### ISSUE THREAD

**Issue by Seebiscuit** [aliostad/CacheCow#108]
I'm trying to prevent certain routes from being cached/added to the cache store (to avoid 304 responses to the client).

I've set up the `HttpCacheRefreshPolicy` initializer in WebApiConfig.cs to the suggested value:

```
cachingHandler.CacheRefreshPolicyProvider = new
  AttributeBasedCacheRefreshPolicy(
  TimeSpan.FromSeconds(30 * 60 * 60 * 24))
  .GetCacheRefreshPolicy;
```

And I've decorated the controllers I want to invalidate cache for, like this:

```
[HttpCacheRefreshPolicy(0)]
[HttpCacheControlPolicy(true, 0, true, true)]
public class DesignationIssuesController : ApiController
{ ... }
```

But the route is still getting cached in the store (I'm using a SQL store) and the value is still getting cached by the Client (Chrome v. 39.0.2171.95 m) and the server is still returning 304.

Am I doing something wrong?

**Comment by aliostad** [comment]
Hi,

Set nostore to false which is not available in 0.6.1:

``` C#
HttpCacheControlPolicy(true, 0, true, true, true)]
public class DesignationIssuesController : ApiController
{ ... }
```

**Comment by TheOtherOnes** [comment]
Hi @aliostad,

I'm also trying to disable caching for certain controllers. I tried the solution described here and the ETag is still returned and stored in the database every time.  It works great for everything, but I don't want to cache everything.

I'm guessing that this behavior is a result of my use of attribute routing with I do understand is not supported.  Unfortunately, I can't change my codebase away from attribute routing.  Can you confirm whether this is truly the cause?  Is there anything else I can do?  My WebApi is GET only.

This is what I tried.

`[HttpCacheRefreshPolicy(0)]`
`[HttpCacheControlPolicy(true, 0, true, true, true, true)]`

I'm using version 0.6.4.

**Comment by aliostad** [comment]
Hi, caching does get disabled per your instructions. @Seebiscuit was asking for these entries not to even appear in the cache which is an improvement to consider.

So yes ETag will be created but your resource will return as the NoCache as you have said it would - so that behaviour works. So the only problem is the overhead on the data store for storing these extra stuff.  If this is your issue, I can look at this when I get some time.
