### ISSUE TITLE
`PUT` on top-level route does not invaldiate cache for child route in different controller

### ISSUE THREAD

**Issue by Seebiscuit** [aliostad/CacheCow#109]
I have a route top level `/domain/{caseId}/Transcripts/Designations/{id}` in a controller named `DesignationsController`. It's decorated with the following attribute:

```csharp

    [HttpCacheControlPolicy(true, 0, true, true)]
    public class DesignationsController : ApiController
    { ... }
```

A child route may be found in  `/domain/{caseId}/Transcripts/Designations/Info/{id}/{designationid}`, which routes to a controller named `DesignationIssues`. It's decorated with the following attributes:

```csharp

    [HttpCacheRefreshPolicy(0)]
    [HttpCacheControlPolicy(true, 0, true, true)]
    public class DesignationIssuesController : ApiController
    { ... }
```

When I do a `PUT` on `/domain/Transcripts/Designations/{id}`, and then I `GET` `/domain/Transcripts/Designations/Info/{id}/{designationid}`, the child route returns a 304 status. 

How can I fix this?

**Comment by aliostad** [comment]
This complex routing is not supported out of box in CacheCow. CacheCow only supports <colection>/<id>

Please implement your own `IRoutePatternProvider`.
