### ISSUE TITLE
Cache not invalidated after PUT in WebAPI with attribute routing

### ISSUE THREAD

**Issue by MesfinReda** [aliostad/CacheCow#110]
Hi Ali,
I was happy to get up and running in few minutes but my cache doesn't seem to be invalidated after put. I have simple webapi that is  api/tenants and I want the list to be updated after PUT is issued to update api/tenant/1 , for example.

Here is what I have in my startup config:
var etagStore = new SqlServerEntityTagStore(connString);
var cacheHandler = new CachingHandler(config, etagStore);
config.MessageHandlers.Add(cacheHandler);

**Comment by aliostad** [comment]
Are you using Attrib routing? since it is not supported.
If you are not and using everything standard, it should. I just quickly doubled checked.

**Comment by MesfinReda** [comment]
Yes. I am using attrib routing. Do you have a plan to support it? If yes, do you have timeline when we should expect the feature? What is the recommended workaround until then?
Thanks!

**Comment by aliostad** [comment]
I am sorry but in the first page, I have already mentioned that it is not supported.
There is no plan to support it in the future.
