### ISSUE TITLE
CacheCow route matching

### ISSUE THREAD

**Issue by Seebiscuit** [aliostad/CacheCow#111]
Does CachCow cache routes solely by path or does it also look at the controller? 

For example say that I have a route:

```csharp
api/cars
```
This route points to `CarsController`. I have another route

```csharp
api/cars/latest
```
that points to `LatestController`. Does a `PUT`/`POST` on one invalidate the cache on the other, even if they live in different controllers?

**Comment by aliostad** [comment]
You can give it a try. By default this should work as it fits the parent/child routing.
