### ISSUE TITLE
TimedEntityTagHeaderValue property 'LastModified' causes issues with SQL Server 2005

### ISSUE THREAD

**Issue by ianrathbone** [aliostad/CacheCow#112]
As server 2005 doesn't support datetimeoffset the SqlServerEntityTagStore fails to work.

However I fixed this for use on the project I'm currently working on by modifying SqlServerEntityTagStore.AddOrUpdate to convert the value to DateTime as follows:

command.Parameters.AddWithValue(ColumnNames.LastModified, eTag.LastModified.DateTime);

**Comment by aliostad** [comment]
I advise against using SQL Server storage for cache - there are plenty of better options such as Redis, Azure Cache, memcached, etc. The implementation exists but will not be maintained much more.
