### ISSUE TITLE
Handling edit conflicts with CacheCow

### ISSUE THREAD

**Issue by gjdownes** [aliostad/CacheCow#114]
I need to implement edit conflict support using the ETag generated by CacheCow server.

Essentially, if a user tries to execute a PUT/PATCH request with an invalid ETag, the server should respond with a 409 or 412 status code and return the current cache value.

Is this functionality built into the library? If so, how do I implement this?

If not, what would you suggest is the best way to implement this feature on top of it.

**Comment by aliostad** [comment]
This functionality is already implemented and one of integral features of CacheCow. It returns 412.
There are unit tests covering this feature, for example:
https://github.com/aliostad/CacheCow/blob/master/test/CacheCow.Tests/Server/CachingHandlerRulesTests.cs#L185
