### ISSUE TITLE
Comparing UTC to non-UTC DateTimes when checking ETag expiries

### ISSUE THREAD

**Issue by memerson** [aliostad/CacheCow#115]
In CacheCow.Server.CachingHandler.CheckExpiry, this code compares a UTC DateTime with a server-timezone DateTime.

<pre>
            if (value.LastModified.Add(cacheExpiry) &lt; DateTimeOffset.Now)
                _entityTagStore.TryRemove(cacheKey);
</pre>

I think you should use DateTimeOffset.UtcNow instead.

The result of this defect is that HttpCacheRefreshPolicyAttribute and AttributeBasedCacheRefreshPolicy don't work on my web server running in Eastern Time.

**Comment by aliostad** [comment]
Hi,

Thanks for using CacheCow.

This should not make a difference:

``` C#
var a = DateTimeOffset.Now;
var b = new DateTimeOffset(a.Add(TimeSpan.FromHours(-5)).Ticks, TimeSpan.FromHours(-5));
Console.WriteLine(a);
Console.WriteLine(b);
Console.WriteLine(a == b);
```

printing
```
03/03/2015 11:54:24 +00:00
03/03/2015 06:54:24 -05:00
True
```

So DateTimeOffset.Now and DateTimeOffset.UtcNow are exactly equal when compared even when Offset is non-zero.


Are you sure this is the cause? Can you please send me a minimal repro?

Thanks
Ali

**Comment by memerson** [comment]
Thanks for looking into it Ali.

I will provide you with a minimal repro this weekend.

By the way, I really love this library!

Cheers,
Matt

**Comment by memerson** [comment]
Hi Ali,

I looked into this a little further and I believe that the issue I found is merely a duplicate of (or at least related to) <a href="https://github.com/aliostad/CacheCow/issues/99">Issue #99<a>.

I'm using the SqlServerEntityTagStore. The DateTimes stored in that table are UTC per the ctor of TimedEntityTagHeaderValue:

<pre>
		public TimedEntityTagHeaderValue(string tag, bool isWeak)
			: base(tag, isWeak)
		{
			LastModified = DateTimeOffset.Parse(DateTimeOffset.<b>UtcNow</b>.ToString(&quot;r&quot;)); // to remove milliseconds
		}
</pre>

That LastModified DateTIme gets read from the DataBase in SqlServerEntityTagStore.TryGetValue. Fresh from the database, the Kind of that DateTime is DateTimeKind.Unspecified, not DateTimeKind.Utc. You assign it to the LastModified property of a TimedEntityTagHeaderValue; that converts it a DateTimeOffset.

<a href="https://msdn.microsoft.com/en-us/library/bb337819.aspx">Per MSDN<a>, when a DateTimeOffset is constructed from a DateTime with a Kind of DateTimeKind.Unspecified, it treats it as a local DateTime, not a UTC DateTime.

So at 10:30am Central Time, I store an ETag. In the database it gets a LastModified of 2015-03-03 16:30:33.000.

I have set a 30 second cache expiry.

In CheckExpiry in the code I pasted in my first message I end up comparing the computed DateTimeOffset with a LocalDateTime of 3/3/2015 4:31:03 PM to DateTimeOffset.Now which has a LocalDateTime of 3/3/2015 10:35:10 AM.

So even though five minutes has actually passed, the expiration check on this ETag fails.

I hope that's clear.

**Comment by memerson** [comment]
The solutions I see are either to <a href="https://msdn.microsoft.com/en-us/library/system.datetime.specifykind%28v=vs.110%29.aspx">specify the kind<a> of every DateTime you read from the database explicitly, or to assume that all DateTimes are UTC and always prefer to use e.g. DateTime.UtcNow, DateTimeOffset.UtcNow, etc... in your code.

I don't know whether this same problem might show up in other ETag or entity stores you provide.

**Comment by IDisposable** [comment]
Just my opinion:
1. Always store ```DateTime``` **any** the database in UTC and **always** assume they are UTC on reading (thus ```SpecifyKind```).
1. Always use ```DateTime.UtcNow``` in server-side code. If a client can/needs to give you a timezone so local times matter (e.g. for a store opening time), then make that an explicit part of the interface. In the case of an HTTP cache, the "client" is the user-agent, and the specification says the timezone is UTC.

**Comment by memerson** [comment]
I believe that these changes will resolve the issue as I experienced it.
