### ISSUE TITLE
Returning Cache-Control header on not modified response

### ISSUE THREAD

**Issue by GDownes** [aliostad/CacheCow#117]
Currently I'm running into the following problem: 

Long setup:

I'm using the CacheCow.Client.CachingHandler with the System.Net.Http.HttpClient

I have a resource that has max-age of 60 seconds.

On the first request to the resource, the resource is not in cache - so the client makes a request to the server, passing back a cache-controller header with the max-age of 60, caching the resource and making the cache valid for 60 seconds. 

On a second request within the 60 second, the cache is still valid, the resource is got from the cache with no request to the server.

On a third request after the 60 seconds, the cache has became stale. The client uses the etag value to validate against the server, which returns a not modified response, and the resource is got from the cache.

This is where my issue begins.

After the not modified response, the cache is still considered stale, meaning that all subsequent requests will validate with the server.

I need to prevent the continuous server validate requests which add extra overhead to my requests. Is there a existing way of doing this? If not my envisioned fix would be:

I would like the resource to be considered valid after a not modified response by returning a cache-control header with a new max-age. Meaning that the resource is considered valid again for a further 60 seconds.

http://stackoverflow.com/questions/1587667/should-http-304-not-modified-responses-contain-cache-control-headers

I can't decide whether a 304 response should make the client cache valid again.

**Comment by aliostad** [comment]
Thanks for raising this.
Yes, this needs to be fixed and I will do it as a priority.

The new HTTP spec is more explicit on this topic:
https://tools.ietf.org/html/draft-fielding-http-p6-cache-00#section-2.5.3

```
   the set of end-to-end headers received in the
   incoming response overrides all corresponding end-to-end headers
   stored with the cache entry (except for stored Warning headers with
   warn-code 1xx, which are deleted even if not overridden).

      Note: this rule allows an origin server to use a 304 (Not
      Modified) or a 206 (Partial Content) response to update any header
      associated with a previous response for the same entity or sub-
      ranges thereof, although it might not always be meaningful or
      correct to do so.  This rule does not allow an origin server to
      use a 304 (Not Modified) or a 206 (Partial Content) response to
      entirely delete a header that it had provided with a previous
      response.
```

**Comment by aliostad** [comment]
OK, it is released in 0.6.3.

Try it out and let me know.

**Comment by GDownes** [comment]
Testing with 0.6.3

Looking at the change(85a1873), on the return of the 304 Not Modified, we aim to update the cachedResponses CacheControl header.
304 Not Modified responses don't return CacheControl headers.

How do I enable the return of the CacheControl header on 304 responses to resolve this issue.

Thanks for the time and great work.

**Comment by aliostad** [comment]
So do you want to enable this on server-side cacheCow? I doubt it does it at the moment, open another issue if that is the case - this was meant for the client side.

**Comment by sudha1981** [comment]
Hello This is Sudhakar Iam using the 1.2.3 version of CacheCow.
detailed procedure : 
1) First time the request comes to web api controller because it is a new request.
2) Second time on wards the request does not hit the controller because we have used the CacheCow caching
http://www.c-sharpcorner.com/article/apply-caching-in-webapi-using-cachecow/
3) The issues is here
Some one is updated the one record in middle in the database but when i hit the API it is returned the old data(Cached data) instead of updated record information.

Please let me know how to fix this issue.

**Comment by aliostad** [comment]
@sudha1981 please open a new ticket. But to answer your question, since your API is not pure (updates do not come from API itself) then there is no way to get around it.
