### ISSUE TITLE
Caching with OData

### ISSUE THREAD

**Issue by SharpLogic** [aliostad/CacheCow#118]
I have an odata enabled web api 2 project.

Simple controller test for a an Account entity.

Single get method that returns all Accounts. /api/Accounts.  Cache works fine I can see the 304 response for subsequent requests.

Now if I do /Accounts?$top=3 - that doesn't use the cache, which I understand as is because the query string makes up the part of the cache key?

So, how would I make /Accounts?$top=3 read from the cache of /Accounts.

It's obviously the same data, I just want a subset and don't really want to hit the database to get it.

This is going to be even more important when using an AutoComplete control for example where its firing contains(Name, 'xxx') as the user types in the box.

Thx

**Comment by aliostad** [comment]
Hi,

Well, from HTTP and REST pov, /Accounts?$top=3 is a different resources to /Accounts. So they would not share the same cache. 

My suggestion is not to pursue sharing cache between these as you soon will hit problems. Having said that, you can implement your own `IRoutePatternProvider` to change this behaviour.

**Comment by SharpLogic** [comment]
It seems like a pretty standard request.

I don't want to keep hitting the repository especially for things like AutoComplete as the user types in a name and I end up with a cache item for 's', 'st', 'ste' etc etc

I'll take a look at the interface!  I have a feeling it's not going to be trivial!
