### ISSUE TITLE
Route pattern invalidatation CacheCow.Client.CachingHandler InMemoryCacheStore

### ISSUE THREAD

**Issue by GDownes** [aliostad/CacheCow#122]
We have the ability to clear the in memory server side cache based on route patterns and linked resources.

The CacheCow.Client.CachingHandler InMemoryCacheStore doesn't feature the ability to invalidate cache items based on route patterns and linked resources. It would be nice to have the ability to invalidate cache objects on the client side mirroring the ability on the server side.

**Comment by aliostad** [comment]
Hi @GDownes 

Would you like to work on it and impl and send a PR?
Achieving it is not trivial since you need to have rich data structures (see Redis impl for comparison) allowing storing lists against a key.

Cheers
Ali
