### ISSUE TITLE
All the controller in WebAPI getting cached implicitly

### ISSUE THREAD

**Issue by Rabisathua-medseek** [aliostad/CacheCow#124]
Hi ,

I have implemented CacheCow in WebApi2 . I have default in memory cache implemented.

 GlobalConfiguration.Configuration.MessageHandlers.Add(new CachingHandler(GlobalConfiguration.Configuration));
 and used  [CacheOutput(ClientTimeSpan = 72000, ServerTimeSpan = 72000)] tag wherever needed in controller apis. There are a lot of controller which is getting cached implicitly , even I have to attribute defined around other controller.

Kindly help regarding the same, as I do not want all the get methods to be cached implicitly.

Thanks,
Rabi

**Comment by aliostad** [comment]
Hi,

`CacheOutput` does not belong to this library.
Please look here for instructions:
http://byterot.blogspot.co.uk/2013/03/rest-asp-net-wep-api-0.4-new-features-breaking-change-cachecow-server.html

**Comment by Rabisathua-medseek** [comment]
Thanks a lot Ali for your reply.I will look into the link you provided.
