### ISSUE TITLE
Cache invalidation for deep url

### ISSUE THREAD

**Issue by pritamkarmakar** [aliostad/CacheCow#127]
Great work Ali and the team.

Quick question regarding cache invalidation. Lets say I have 2 actions 
````
UpdateProfile(Profile profile) and 
GetProfile(string userid)
````

I want to invalidate GetProfile for a user who will make the UpdateProfile call, but for other users it shouldn't invalidate the cache. How I can do this? Thanks in advance.

**Comment by aliostad** [comment]
HTTP Caching is based on URL so items are gets cached or invalidated based on the URL. As long as the "customer Id" is on the URL as a route segment or query string, it should be all fine.

You can give it a go and try out to confirm this is indeed the behaviour.

Hope this helps.
