### ISSUE TITLE
Handling Transient Failures when using SQL Azure

### ISSUE THREAD

**Issue by benfoster** [aliostad/CacheCow#129]
Microsoft recommend that you implement retry logic when working with SQL Azure. If you don't, as we've experienced, a connection failure will result in failed request.

To implement the retry logic we can use the `Microsoft.Practices.EnterpriseLibrary.TransientFaultHandling` package that provides a `ReliableSqlConnection`, encapsulating the retry behaviour. 

Currently the `SqlEntityTagStore` does not allow us to override how the connection is created. We've implemented our own `SqlAzureTagStore` that allows you to pass a connection string factory. This was sufficient to support both standard SQL Connections and the one with retry logic - see https://gist.github.com/benfoster/14cb8d99f6f47f9d274b. 

I had to swap out some of the System.Data.Sql methods with the more generic System.Data alternatives.

Would you like me to send a pull request to update the existing `SqlEntityTagStore` or do you believe this belongs in a different package.

On a different note, should such exceptions not be caught by CacheCow? Right now, if the caching handler fails it results in a 500 error. I'd rather that the response succeeds if caching fails than taking down our API.

**Comment by aliostad** [comment]
By all means. Please send your PR.

**Comment by aliostad** [comment]
Are you gonna do this?

**Comment by benfoster** [comment]
I made the change but it ended up making no difference. SQL Azure is just a
bad choice for a cache store.

On 24 August 2015 at 13:05, Ali Kheyrollahi <notifications@github.com>
wrote:

> Are you gonna do this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aliostad/CacheCow/issues/129#issuecomment-134166990>.
>



-- 

Ben Foster
planetcloud

*fabrik.*
The portfolio and blogging service for creatives.
info@getfabrik.com
http://getfabrik.com

**Comment by aliostad** [comment]
abso. So it seems I need to close this.
