### ISSUE TITLE
About cache in specific methods

### ISSUE THREAD

**Issue by rafakwolf** [aliostad/CacheCow#132]
Hello...

It is possible to set in a specific method, a cache duration?

Or some other method to do that ?

Thanks

**Comment by ronnelsantiago** [comment]
have u looked at http://byterot.blogspot.com.au/2013/03/rest-asp-net-wep-api-0.4-new-features-breaking-change-cachecow-server.html 

basically its an attribute you put on your web api method..

**Comment by rafakwolf** [comment]
Hello, thanks for your answer, but...i have configured my Startup.cs class:

var config = new HttpConfiguration();            
var cacheHandler = new CachingHandler(config);
config.MessageHandlers.Add(cacheHandler);

And then in my controller:

[RoutePrefix("pessoaPerfil")]
[HttpCacheControlPolicy(true, 100)]
public class PessoaPerfilController : BaseController
{
        [Route("{id}")]
        [HttpCacheControlPolicy(true, 100)]
        [DeflateCompression]
        public IHttpActionResult Get(int id)
        {
        }
}

Even then the header response is like this:

**Cache-Control → no-transform, must-revalidate, max-age=0, private**

The Get method is called always.
I'm doing something wrong?

Thanks!

**Comment by ronnelsantiago** [comment]
make sure you are re using your httpclient instance.. i.e. not new-ing it up every time..

**Comment by rafakwolf** [comment]
I'm sorry, what you mean ?

If i call a method directly from the browser, the cache doesn't works ?

**Comment by rafakwolf** [comment]
I'm not using a .NET httpclient...is an angularJS client.

**Comment by ronnelsantiago** [comment]
are you using attribute based routing or convention based routing? from the documentation it mentioned that its not working for attribute based routing..

**Comment by rafakwolf** [comment]
Ok, thanks for your attention.

**Comment by aliostad** [comment]
Thanks @ronnelsantiago !!
