### ISSUE TITLE
RedisEntityTagStore only generates Weak ETags

### ISSUE THREAD

**Issue by bl1nkr** [aliostad/CacheCow#133]
I am using the pre-release for Server.EntityTagStore.Redis and it only generates Weak Tags.  I have tried on two different Redis servers.

my config is pretty basic

`var eTagStore = new RedisEntityTagStore("connGoesHere");'
'var cacheCowCacheHandler = new CacheCow.Server.CachingHandler(config, eTagStore);`
`config.MessageHandlers.Add(cacheCowCacheHandler);`

Any ideas? Thanks for your help!

**Comment by aliostad** [comment]
Hi, 

Try to update the CacheCow.Server using

```
PM> update-package CacheCow.Server
```

Since I believe the latest version creates strong etags.

In any case, all you have to do is to change the ETag generator to return strong ETags, something like:

``` csharp
handler = ETagValueGenerator = () => "\"" Guid.NewGuid().ToString() + "\"";
```

Hope this helps.
