### ISSUE TITLE
Backend Processes and CacheCow?

### ISSUE THREAD

**Issue by bl1nkr** [aliostad/CacheCow#134]
Hello Sorry for probably a dumb question.  But how does CacheCow work with backend processes which will alter the data?

thanks!

**Comment by aliostad** [comment]
Hi, sorry for a late reply.

It obviously cannot automatically detect the changes in underlying resource but it allows you to invalidate the cache by calling `InvalidateResource`.

Does this answer the question?

**Comment by bl1nkr** [comment]
yes thank you!
