### ISSUE TITLE
returning cached resource, on 404

### ISSUE THREAD

**Issue by drzoidb3rg** [aliostad/CacheCow#136]
Any advice here is welcome. I have noticed that fof 404, this line

https://github.com/aliostad/CacheCow/blob/master/src/CacheCow.Client/CachingHandler.cs#L417

removes the entry from the cache. For fault tolerance reasons,  I would like to keep entries if a 404 exists and return the item in the cache ( even it it is stale)

How would I do this ?

**Comment by aliostad** [comment]
Hi,

HTTP Spec is very vague on this but my take is unsuccessful responses must not be cached - apart from 410. 

Having said that, I have provided extension points for this to be overriden. Have a look here:
https://github.com/aliostad/CacheCow/blob/master/src/CacheCow.Client/CachingHandler.cs#L65

You just need to provide your own `ResponseValidator` and perhaps copy the code and change L65 (successful result) and remove the check for response.StatusCode.IsIn(_cacheableStatuses) which you wouldnt have access to anyway.

**Comment by drzoidb3rg** [comment]
Hi thanks for this. I already implement my own ResponseValidator. The issue is,  if a resource was available and cached, but a subsequent request gets a 404, because the server is down, I wanted to return the cached version. The current implementation will automatically delete the cached resource in this scenario

**Comment by aliostad** [comment]
Sorry I do not understand, can you not check for the existence of item and if 404, return cacheable?

**Comment by drzoidb3rg** [comment]
Sure, but the cache cow handler removes the item from cache if 404.

**Comment by aliostad** [comment]
But only if validationResult is not MustRevalidate or OK... which is under your control, no?
