### ISSUE TITLE
CacheCow implementation questions

### ISSUE THREAD

**Issue by josunedesosa** [aliostad/CacheCow#138]
Hi ,
I want to know if you have any manual to use cachecow in a client and in the WebAPI 2.
I perform a little example (CRUD application) to check the cachecow but all the time the client call the WebAPI and not use the cache information and I don´t know why. For example, If I execute two Get actions sequentially to obtain the list of products, the webapi return two times the list and not the cache object in the second call.  I am using the last version of CacheCow 0.6.4.  and I implement the solution as explained below:
In the WebAPI solution, in WebApiConfig.cs file, I have added next line for the cache:
                config.MessageHandlers.Add(new CacheCow.Server.CachingHandler(config));
 
In WPF  solution, when I have created the httpclient we add these lines:                
                               HttpClient httpClient = new HttpClient(new CachingHandler() { InnerHandler = new HttpClientHandler() });
         If I change these lines for these others, 
             HttpClient httpClient = new HttpClient(new WebRequestHandler()
             {
                    CachePolicy = new RequestCachePolicy(RequestCacheLevel.Default)
             });

             the client only call the webapi the first time that I execute the Get action and in Delete,  Update and Insert actions. If I perform these actions: 
1)      Get produts (obtain products of WebAPI), 
2)      Get products (obtain products of cache)
3)      Add a new product (call the WebAPI to add a new product) 
4)      Get products (obtain productos of cache) => his should get the new products from WebAPI because it has changed.

What am I doing wrong?

Best regards,

**Comment by aliostad** [comment]
Are you using AttributeRouting? Because that is not supported with CacheCow.

**Comment by josunedesosa** [comment]
Yes I am using AttributeRouting. This is the problem. Thank you!!
