### ISSUE TITLE
Why the third time that I execute the get action the data is obtained from the api and not from the cache?

### ISSUE THREAD

**Issue by josunedesosa** [aliostad/CacheCow#139]
Hello,

I have a very simple example and when I perform the get (of a list of elements) to webapi repeatedly I have problems. If I perform this action three times, in the first time the list is obtained from the api, the second is obtained from the cache and in the third,  the list is obtained from the api. Why??? I don´t understand because I have not performed any other action.
I am using in the client:

            HttpClient httpClientCache = new HttpClient(new CachingHandler() { InnerHandler = new HttpClientHandler() });

and in the server:

            CachingHandler cacheHandler = new CachingHandler(GlobalConfiguration.Configuration);            
            GlobalConfiguration.Configuration.MessageHandlers.Add(cacheHandler);

without attributerouting.

What am I doing wrong?

Thanks.

Josune

**Comment by aliostad** [comment]
Are you using Owin handlers? That is not supported yet either.

**Comment by josunedesosa** [comment]
Can you tell me where I can find options that do not support CacheCow?
You have planned to implement CacheCow to support Owin?

**Comment by aliostad** [comment]
Sorry for the delay. I have now reproduced it. I will get back to you.

**Comment by aliostad** [comment]
OK, I found out.

First of all, there was a bug in the commented code:

      var initialResponseHeader3 = initialResponse.Headers.Single(
            x => x.Key == CacheCowHeader.Name).Value.First();

Here `initialResponse` must be `initialResponse3`!

But the main issue here is that by default, MaxAge is set to 0 which is pretty much means no caching. If you set it to another value, problem goes away:

```
          CachingHandler cacheHandler = new CachingHandler(GlobalConfiguration.Configuration);
            cacheHandler.CacheControlHeaderProvider = (message, configuration) => new CacheControlHeaderValue()
            {
                MustRevalidate = true,
                MaxAge = TimeSpan.FromHours(1),
                Private = true
            };
            GlobalConfiguration.Configuration.MessageHandlers.Add(cacheHandler);
```

Having said that, I think there is still a bug which the result of 304 seems to remove item from the cache. I will look into it.

**Comment by aliostad** [comment]
OK, I have not tested this and now that it works. Have a look at this test `ZeroMaxAgeShouldAlwaysComeFromCacheIfNotChanged `. It should check for your case and it is working.

https://github.com/aliostad/CacheCow/blob/master/test/CacheCow.IntegrationTesting/IntegrationTests.cs#L67
