### ISSUE TITLE
NuGet package for CacheCow.Server not strong named. Now I cannot use it

### ISSUE THREAD

**Issue by Jaans** [aliostad/CacheCow#141]
I was so looking forward to giving CacheCow a go, but the NuGet package doesn't ship a strong named assembly.

`Referenced assembly 'CacheCow.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

Please fix!

**Comment by aliostad** [comment]
OK, let me see what is the effort involved. I have been asked for this before as well and I have a few days off so could work on it.

**Comment by Jaans** [comment]
That would be great! Thank you!

**Comment by aliostad** [comment]
@Jaans which projects do you actually need? Out of storages, only Azure and MongoDb can be strong named since other projects depend on unsigned assemblies.

**Comment by Jaans** [comment]
@aliostad Thanks for the feedback!
I would suggest the assemblies from the following NuGet Packages are a minimum for strong naming:
CacheCow.Common
CacheCow.Server
CacheCow.Client

As for the storage providers, we use File, SQL and Azure on the server. Client-side is less of a scenario for us, but I suspect that if you get your dependencies (e.g. CacheCow.Common+Server+Client) strong named it might be viable for other assemblies.

Which projects are depending on unsigned assemblies?

**Comment by aliostad** [comment]
Those 3 not a problem. I am afraid File and SQL would not make it - they depend on unsigned - and I generally suggest stay away from them because they are not optimised. 

So I will release these - hopefully today.

**Comment by Jaans** [comment]
Great... thanks for that!

**Comment by aliostad** [comment]
These are released now. e.g. https://www.nuget.org/packages/CacheCow.Common.sn/1.1.1

**Comment by jagbarcelo** [comment]
It seems those three assemblies (CacheCow.Common.sn, CacheCow.Server.sn & CacheCow.Client.sn) 
were left in version 1.1.1.

Any chances to update them to their latest version (2.4.2)? Thanks in advance.
