### ISSUE TITLE
304 (Not Modified) does not update the Client cache properly

### ISSUE THREAD

**Issue by Reyhn3** [aliostad/CacheCow#142]
Hi!

Consider the following scenario:

1. The client requests an entity for the first time, and receives 200 (OK).
2. The client requests the same entity within the valid cache time, and receives the entity from the client cache.
3. The client requests the same entity a third time, but the max-age has expired the client-side cached entity, and a request is sent to the server. The server responds with 304 (Not Modified) and the client-side cached entity is returned.
4. From now on, requesting the entity will always invoke a call to the server.

The bug is that the client-side **CachingHandler** never updates the **Date header** on the cached entity response. The client-side CachingHandler always believes that the entity must be revalidated.

According to #123, the server-side CachingHandler always returns a null cache-control header. The CacheCow.Client.CachingHandler.**UpdateCachedResponse**-method ignores all 304-responses with null-headers and subsequently never updates the date-header. Thus the ResponseValidator returns MustRevalidate forever.

**Comment by aliostad** [comment]
Thanks @Reyhn3 
I feel you are right and it is a bug. Let me double check and if that is the case, I would need to fix and release.

**Comment by aliostad** [comment]
FIx provided by @Reyhn3
