### ISSUE TITLE
CacheCow Redis packages built against StackExchange.Redis.StrongName

### ISSUE THREAD

**Issue by russcam** [aliostad/CacheCow#144]
I would like to use the CacheCow redis packages in an MVC project that also uses the Redis SessionStateProvider package written by Microsoft. 

An issue arises here in that the Redis SessionStateProvider package is built against the signed version of StackExchange.Redis, [StackExchange.Redis.StrongName](https://www.nuget.org/packages/StackExchange.Redis.StrongName/), but CacheCow Redis components are built against the unsigned version of StackExchange.Redis.

Would it be possible to provide versions of CacheCow Redis components built against the signed version of StackExchange.Redis?

**Comment by aliostad** [comment]
I am not sure how I missed this. Sorry Russ, this is old please let me know if is a problem

**Comment by russcam** [comment]
No worries @aliostad; ended up internally signing CacheCow to get around this. I'm no longer working at the same place so not sure if it's still an issue.

**Comment by aliostad** [comment]
I believe you are with @elastico which is very cool!

**Comment by russcam** [comment]
> I believe you are with @elastico which is very cool!

@elastic, yep 😄
