### ISSUE TITLE
CacheCow.Server.EntityTagStore.Redis has invalid CacheCow.Server Dependency

### ISSUE THREAD

**Issue by jblackburn21** [aliostad/CacheCow#147]
I'm trying to use the 1.1.0 version of the CacheCow.Server.EntityTagStore.Redis package from NuGet, but it has an invalid dependency on CacheCow.Server:

CacheCow.Server (≥ 1.1.0)

The latest version of CacheCow.Server on NuGet is 1.0.0.

Thanks!

**Comment by aliostad** [comment]
Sincere apologies. 1.2 uploaded now which is the latest although not a change from earlier version.
