### ISSUE TITLE
Request to have CacheCow.Server.EntityTagStore.SqlServer to be strong name

### ISSUE THREAD

**Issue by wkit23** [aliostad/CacheCow#148]
Is it possible to have a nuget package for CacheCow.Server.EntityTagStore.SqlServer with strong name?

**Comment by aliostad** [comment]
Sorry do you still need this?

**Comment by wkit23** [comment]
Yes please, if possible. At the moment I'm just getting the whole source and sign it myself. It would be great to exclude external sources and just use them as reference via nuget.

**Comment by aliostad** [comment]
This project does not exist anymore.
