### ISSUE TITLE
Generate CacheKey for distinct users

### ISSUE THREAD

**Issue by gjdownes** [aliostad/CacheCow#149]
I'd like to cache a user-specific resource (i.e. the given resource should only be visible for one user and cached specifically for that user).

My route pattern is: "/messages", so there's no identifying info in the uri to make the cache key unique.

I identify the user based on an access token passed in the request Authorization header. Is it possible to override the CacheKey implementation to generate the hash using a "UserID" property? I extract the user id value from the RequestContext.Principal.Identity object.

**Comment by aliostad** [comment]
Hi,

sorry for the delay.

This is the signature of ETagGenerator:

``` C#
public Func<string, IEnumerable<KeyValuePair<string, IEnumerable<string>>>,
			EntityTagHeaderValue> ETagValueGenerator { get; set; }
```

So it is a function like:

``` C#
private EntityTagHeaderValue BuildETag(string url, IEnumerable<KeyValuePair<string, IEnumerable<string>>> requestHeaders)
{
    // ... build your etag using auth header
}
```

So all you have to do is to set the ETagValueGenerator:
```
cachingHandler.ETagValueGenerator = BuildETag;
```

I suggest, instead of user id (which you would not have access to), use a hash of the identity token in the auth header which serves the same purpose.

Is that OK?

**Comment by gjdownes** [comment]
It may work, although the auth token value will change every 20mins or so which means the cached value will be invalid after the same period.

What I could do is add a custom header value with a more persistent value to act in the same capacity.

Thanks for looking into this.

**Comment by aliostad** [comment]
yeah I thought the expiry of the token could be a problem. What are you using for your security? I have looked into the OWIN middlewares and should be possible to add the a custom header there. Or perhaps a delegating handler that extracts and as you said sticks it in a header.

Hope it works for you.
