### ISSUE TITLE
Clear resource by pattern

### ISSUE THREAD

**Issue by benfoster** [aliostad/CacheCow#150]
Bit of a long shot but is it possible to clear all cache entries with a Resource URI that matches a specified pattern?

We're using the Redis tag store and occasionally we have to update data outside of our API. Our API is multi-tenant and these updates effect every tenant.

E.g.

```
/sites/1/themes/*
/sites/1/themes/1
/sites/1/themes/1/configuration
/sites/2/themes/*
...
```

All of the above resources use a source "Theme Definition" document. When this is updated I need to invalidate all of these resources (anything that contains "themes").

I have a feeling I'm going to have to remove these directly in Redis?

**Comment by aliostad** [comment]
sorry is not this the method to call?

```
int RemoveAllByRoutePattern(string routePattern);
```

I believe it has been implemented.

**Comment by benfoster** [comment]
Thanks for the reply. Unfortunately since this is a multi-tenant application and the implementation doesn't do wildcard matching this wouldn't work.

The site id in my previous example is effectively our tenant id. We'd need to somehow do a wildcard match like:

/sites/*/themes/*

**Comment by aliostad** [comment]
Moving away from that pattern in 2.0.0
