### ISSUE TITLE
Getting strong ETag for in-memory caching

### ISSUE THREAD

**Issue by ruchitanehete** [aliostad/CacheCow#151]
I am trying to implement a simple Web API2 application to use CacheCow for in-memory caching.
Following are the steps which I implemented to achieve this :
1. Installed CacheCow.server 1.2 library through NuGet
2.Registered the cache handler as below in Web API config file.
GlobalConfiguration.Configuration.MessageHandlers.Add(new CachingHandler(GlobalConfiguration.Configuration));

Now When I try to execute the GET request using Postman, I am not able to get the weak ETag instead I always get a strong ETag value. I am unable to understand if my resource is cached or not. Am I missing something to implement?
Also I want to remove all the cached resources.

**Comment by aliostad** [comment]
Week/Strong ETag is related to whether the ETag applies to semantic vs. verbatim changes of the resource:

> Entity tags are normally "strong validators," but the protocol provides a mechanism to tag an entity tag as "weak." One can think of a strong validator as one that changes whenever the bits of an entity changes, while a weak value changes whenever the meaning of an entity changes. Alternatively, one can think of a strong validator as part of an identifier for a specific entity, while a weak validator is part of an identifier for a set of semantically equivalent entities.

So this does not apply.

Clearing all cached resources is dependent on the storage, the interface not provided on the `IEntityTagStore`.
