### ISSUE TITLE
Unable to resolve dependency 'CacheCow.Common (≥ 1.2.1)

### ISSUE THREAD

**Issue by kpstolk** [aliostad/CacheCow#155]
When I try to install CacheCow.Client 1.2.1, I get an installation error with NuGet:

> 
> Attempting to resolve dependency 'CacheCow.Common (≥ 1.2.1)'.
> Unable to resolve dependency 'CacheCow.Common (≥ 1.2.1)'.

When I search NuGet for [CacheCow.Common](https://www.nuget.org/packages/CacheCow.Common/) the latest available version is 1.2.0 and not 1.2.1.

So where did CacheCow.Common version 1.2.1 go?

**Comment by aliostad** [comment]
Thanks for reporting. Yes I will push that tomorrow. 

In the meantime please use 1.2 since 1.2.1 fixes a minor and unlikely bug

**Comment by aliostad** [comment]
Pushed the version.

**Comment by kpstolk** [comment]
Thank you, I can confirm that the package is available now and can be installed. :)

**Comment by aliostad** [comment]
Cheers! Thanks for reporting.
