### ISSUE TITLE
"This operation is not supported for a relative URI" on POSTs

### ISSUE THREAD

**Issue by jagbarcelo** [aliostad/CacheCow#160]
We are trying to use your CacheCow (Server & Client) into our API (still under early stages of development). Right now it seems to work fine with GETs but as soon as we have tried with some POSTs we are receiving the following Exception:

```
{
 "Message": "An error has occurred.",
 "ExceptionMessage": "This operation is not supported for a relative URI.",
 "ExceptionType": "System.InvalidOperationException",
 "StackTrace": "at System.Uri.get_AbsolutePath()\r\n   at CacheCow.Server.CachingHandler.InvalidateResource(HttpRequestMessage request)\r\n   at CacheCow.Server.CachingHandler.<>c__DisplayClass11.<PostInvalidationRule>b__10()\r\n   at CacheCow.Common.Helpers.BasicExtensions.<>c__DisplayClass4.<Chain>b__3() ..."
}
```

It seems it is something similar to your issue https://github.com/aliostad/CacheCow/issues/92

You clearly state in the project homepage that "_Currently CacheCow's attribute setting does not work with Attribute Routing_" but I don't know if this is exactly our case. We do not make any use of [Route("blah")] nor [RoutePrefix("blah")] and yet we still receive this Exception.

In our WebApiConfig.cs we have the usual: `config.MapHttpAttributeRoutes();`
along with a couple of Routes, your code and another for compression:
```
            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/v1.0/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional },
                constraints: new { id = @"^(([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})|(\d+))?$" } // Either a guid or an integer (optionally none)
            );

            config.Routes.MapHttpRoute(
                name: "Controller+Action",
                routeTemplate: "api/v1.0/{controller}/{action}",
                defaults: new { action = RouteParameter.Optional },
                constraints: new { }
            );

            config.Routes.MapHttpRoute(
                name: "Controller+Id+Action",
                routeTemplate: "api/v1.0/{controller}/{id}/{action}",
                defaults: new { id = RouteParameter.Optional, action = RouteParameter.Optional },
                constraints: new { id = @"^([0-9A-F]{8}-([0-9A-F]{4}-){3}[0-9A-F]{12})?$" } // Only optional guids
            );

            // https://github.com/aliostad/CacheCow/wiki/Getting-started
            var connectionString = System.Configuration.ConfigurationManager.ConnectionStrings["MyConnectionString"].ConnectionString;
            var eTagStore = new CacheCow.Server.EntityTagStore.SqlServer.SqlServerEntityTagStore(connectionString);
            GlobalConfiguration.Configuration.MessageHandlers.Add(new CacheCow.Server.CachingHandler(GlobalConfiguration.Configuration, eTagStore));

            // https://github.com/azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression
            GlobalConfiguration.Configuration.MessageHandlers.Insert(0, new ServerCompressionHandler(new GZipCompressor(), new DeflateCompressor()));

```

We have also tried it commenting out the CompressionHandler (at the end), without any luck (the problem does not seem to have anything to do with it being or not being used).

Any suggestion?

**Comment by jagbarcelo** [comment]
FYI, and any other that might face the same problem:

I have isolated the problem (for my case) and found a fix for it. The issue appeared because our API methods were returning IHttpActionResult and at the end of them there were lines as `return Created<string>("DefaultApi", value); `

We have just changed them all into `return Created<string>(Request.RequestUri.AbsoluteUri, value);` and the exception has gone for good.

**Comment by aliostad** [comment]
Thanks @jagbarcelo !

It is great to know and thanks a lot for your contribution.
