### ISSUE TITLE
Should CacheCow.Client cache this response?

### ISSUE THREAD

**Issue by benfoster** [aliostad/CacheCow#161]
This is the HTTP response I'm getting from Vimeo's API:

```
HTTP/1.1 200 OK
Server: nginx
Content-Type: application/vnd.vimeo.video+json
Cache-Control: no-cache, max-age=315360000
Strict-Transport-Security: max-age=15120000; includeSubDomains; preload
Last-Modified: 1461924756
Expires: Mon, 27 Apr 2026 10:28:54 GMT
Content-Encoding: gzip
Via: 1.1 varnish
Fastly-Debug-Digest: 45a33937eb07618f58bc572812ad46a0f248dab09115eb0bbd6951976f37b45f
Content-Length: 938
Accept-Ranges: bytes
Date: Fri, 29 Apr 2016 10:28:54 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-iad2126-IAD, cache-lhr6332-LHR
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
X-Timer: S1461925734.185994,VS0,VE114
Vary: Accept,Vimeo-Client-Id,Accept-Encoding
```

I know it specifies `no-cache` but it also `max-age` and `Last-Modified` set.

I thought CacheCow.Client should therefore cache the response?

**Comment by IDisposable** [comment]
Yes, it should certainly cache the response... but it should not yield it back to the client without doing a ETag / Last_Modified check If-None-Match and If-Modified-Since request.

https://jakearchibald.com/2016/caching-best-practices/

**Comment by aliostad** [comment]
First of all, this Last-Modified is invalid according to RFC 2616, did not check against the latest. Since it is invalid, I guess the client cannot make a conditional GET since no valid Last-Modified or ETag.

As IDisposable said `no-cache` means that the item is cacheable but the client has to check with server.

**Comment by IDisposable** [comment]
Oh, sorry, totally didn't notice the date wasn't a date (looks like a tick count)
