### ISSUE TITLE
ASP.NET Core support

### ISSUE THREAD

**Issue by totht91** [aliostad/CacheCow#162]
Hello!

Is there any plans to support the .NET Core framwork, and work with ASP.NET Core?

THX

**Comment by aliostad** [comment]
Hi,

Yes, I am planning to move the CLIENT part to ASP.NET Core. However, for reasons that I am sure you are aware of, core has been undergoing a lot of change so I need to wait for it to stabilise before taking it across. 

But I can confirm this will be done.

**Comment by thegrindr** [comment]
Thank you.

**Comment by ThinkAboutGitHub** [comment]
Hi aliostad will you be moving the SERVER part to ASP.NET Core aswell?
