### ISSUE TITLE
Memory leak imminent when using CacheCow.Client.CachingHandler with non-singleton ICacheStore

### ISSUE THREAD

**Issue by slawomir-brzezinski-at-interxion** [aliostad/CacheCow#163]
Hi. Our code is as follows:

```
using (var client = new HttpClient(
                    new CachingHandler(
                        new RedisStore(...)
                    )
                    { InnerHandler = new HttpClientHandler() }
))
{
    Do something with the client.
}
```

(the real scenario actually has the whole construction extracted to a factory method)

This CachingHandler constructor (declared [here](https://github.com/aliostad/CacheCow/blob/master/src/CacheCow.Client/CachingHandler.cs#L48)) leaves the `_disposeCacheStore` flag unassigned, effectively making it `false`.

The RedisStore used here is something that leaks many resources if not disposed and this is exactly what happens, because this API doesn't even leave an option to dispose it.

I understand that https://github.com/aliostad/CacheCow/issues/47#issuecomment-137622213 has requested for the cache store to not be disposed by default, which caters for the cases when it's coming from an IoC container's singleton instance.

But using a case like above is also a valid use scenario, so there should at least be a constructor overload which allows to pass the `ICacheStore` as well as the flag to initialize the `_disposeCacheStore` field.

**Comment by IDisposable** [comment]
Ideally the simplest thing would be to just make the two `_dispose*Store` flags settable as properties thus:
```
public bool DisposeCacheStore { get { return _disposeCacheStore;  } set {  _disposeCacheStore = value; } }
public bool DisposeVaryStore { get { return _disposeVaryStore;  } set {  _disposeVaryStore = value; } }
```
Then your construction would look like
```
using (var client = new HttpClient(
                    new CachingHandler(
                        new RedisStore(...)
                    )
                    { InnerHandler = new HttpClientHandler(), DisposeCacheStore = true }
))
{
    Do something with the client.
}
```

**Comment by slawomir-brzezinski-at-travcorp** [comment]
After some thinking IMHO this flag is so important that the default should rather be true.

I'd side here with the fail-fast philosophy (e.g. see [Fowler](http://martinfowler.com/ieeeSoftware/failFast.pdf)). Namely here, I'd rather found out second time I try to use a component that my singleton is already disposed, which very likely to surface during development, and is pretty easily fixable (with a wrapper around `ICacheStore`, like suggested [here](https://github.com/aliostad/CacheCow/issues/47#issuecomment-137631239), telling IoC container to set the flag to `false`, or doing it in own subclass of your `CachingHandler`), rather than have a a memory leak, which very often surfaces as late as production (like in our case).

If error on second use is even too late, you can to make it even safer and have the error pop out on first use, by not providing any default, i.e. always require a flag next to `ICacheStore` in the constructor.

The current behavior is less safe than any of two above.

**Comment by aliostad** [comment]
Hi, and sorry.

In general terms, whoever makes creates disposable objects (owning them) should dispose them. Store could be shared among multiple clients hence disposing should be done outside.

Having said that, the _disposeCacheStore is set to true by default.

I know, it is an old issue but I am releasing 2.0.0 and would like to close these. If still an issue, let me open again.

**Comment by zlamma** [comment]
> Having said that, the _disposeCacheStore is set to true by default

If it's really `true` now, then that pretty much addresses the problem as [I suggested](https://github.com/aliostad/CacheCow/issues/163#issuecomment-233078034).

Thanks!

**Comment by aliostad** [comment]
@zlamma thank you and so sorry for the massive delay.
I have not been happy with Server-side caching story and now and I have fixed and ready for 2.0.0 so this time will try harder to keep on top of issues.

**Comment by zlamma** [comment]
Regarding:  

> In general terms, whoever makes creates disposable objects (owning them) should dispose them.

Generally, I agree this is a good rule, but this rule has a limit. When the only way a disposable resource is used is through one wrapper/decorator/composite then it it really useful to not make them leaky abstractions.

One good example is .NET `StreamReader`, which, according to [the docs](https://msdn.microsoft.com/en-us/library/yhfzs7at(v=vs.110).aspx):
_'calls Dispose() on the provided Stream object when StreamReader.Dispose is called.'_

I don't know if other people really put their `RedisStore` instance to some other uses but, at least in our case, the only reason for its existence was that CachingHandler.

**Comment by aliostad** [comment]
Would be good if you can have a look at the beta 2.0.0. It now supports .NET Core too and client has not changed really so should work OOB (cannot remember any breaking change).

**Comment by slawomir-brzezinski-at-interxion** [comment]
This is certainly good news as we are gradually migrating to .NET Core, but, since this is client's commercial software, I'm afraid we will only be able to move to it once it's out of the prerelease version.

**Comment by aliostad** [comment]
release is coming soon. Preview version is already out.
