### ISSUE TITLE
Cache with Accept-Language 

### ISSUE THREAD

**Issue by flowdopip** [aliostad/CacheCow#164]
Hi,

My API could have different response´s based on Accept-Language (Translated Content), it there any way to add this to the RoutePattern? I´ve try to override   GetRoutePattern but doesnt work?

This could be a valid solution?
Thanks

**Comment by aliostad** [comment]
Hi,

No... all you have to do is to set the `VaryHeaders` to `new [] {"Accept", "Accept-Language"}` resulting in Accept-language value considered in the cache key.

Any problems let me know.

**Comment by flowdopip** [comment]
Thanks,

I had not noticed that we can set vary params on handler ctor.
