### ISSUE TITLE
Disable Cache for several actions

### ISSUE THREAD

**Issue by flowdopip** [aliostad/CacheCow#165]
Hi,

Im trying to prevent cache or add different times for expiration for several actions.

Follow my setup:

 var etagStore = new RedisEntityTagStore(redisDatabase.GetDatabase(), TimeSpan.FromMinutes(20));

                var httpCacheHandler = new CacheCow.Server.CachingHandler(config, etagStore, new[] { "Accept", "Accept-Language" })
                {
                    AddVaryHeader = true,
                    CacheControlHeaderProvider =
                    new AttributeBasedCacheControlPolicy(
                        new System.Net.Http.Headers.CacheControlHeaderValue()
                        {
                            NoStore = false,
                            NoCache = true

                        }).GetCacheControl,
                    CacheRefreshPolicyProvider = new AttributeBasedCacheRefreshPolicy(TimeSpan.FromSeconds(60)).GetCacheRefreshPolicy
                };

on the controller i have the follow code:

   [HttpCacheRefreshPolicy(0)]
        [HttpCacheControlPolicy(true, 0, true, true, true,true)]
        [Route(""), ResponseType(typeof(List<City>))]
        public async Task<IHttpActionResult> GetAll([FromUri] int? countryId = null)

can you help me with this?
thanks

**Comment by aliostad** [comment]
Hi,

I am afraid CacheCow does not work with AttributeRouting. Is that what you are using?

**Comment by flowdopip** [comment]
Ups, ya! Sorry this is the problem!

Do you will try to have a solution for AttributeRouting? It´s there a way to do it, based on cache cow!

**Comment by aliostad** [comment]
I am afraid not. CacheCow.Server will be completely changing in the dotnetcore. I am waiting for stabilisation to port.
