### ISSUE TITLE
CacheCow to ASP.NET Core?

### ISSUE THREAD

**Issue by ThinkAboutGitHub** [aliostad/CacheCow#166]
Hi, will you be moving the SERVER part of CacheCow to ASP.NET Core?

**Comment by aliostad** [comment]
Not in this form. There needs to be some major changes since current design is somehow flawed. Main issue is that an API layer cannot assume responsibility of maintaining the freshness of cache, only data store can. 

I will start looking into it when the .NET core tooling is more stable.

**Comment by ThinkAboutGitHub** [comment]
Thanks aliostad. Are there any other alternatives to CacheCow you can recommend in the meantime?
