### ISSUE TITLE
NullReferenceException in CachingHandler when cached response doesn't contain Cache-Control header

### ISSUE THREAD

**Issue by joostvz** [aliostad/CacheCow#168]
Hi,

I receive the following response from a server which I'd like to cache using CacheCow:
_HTTP/1.1 200 OK
Date: Wed, 14 Sep 2016 07:45:13 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 5308_

The response is missing a Cache-Control header. As a result, a NullReferenceException occurs in the CachingHandler on the following line when the 2nd request is retrieved from the cache:
_TraceWriter.WriteLine("{0} - Existed in the cache. CacheControl Headers => {1}", TraceLevel.Verbose, request.RequestUri.ToString(), cachedResponse.Headers.CacheControl.ToString());_

Is this a CacheCow issue, or should the server always send the Cache-Control header?

**Comment by kpstolk** [comment]
Looks like [line 296 in CachingHandler.cs](https://github.com/aliostad/CacheCow/blob/master/src/CacheCow.Client/CachingHandler.cs#L296).

@aliostad Maybe as easy as adding a questionmark after the `CacheControl` property to prevent the NRE?:
`cachedResponse.Headers.CacheControl?.ToString()`

As far as I can find ([RFC7234](https://tools.ietf.org/html/rfc7234#section-5.2)) the `Cache-Control` header isn't required and may not be implemented, like @joostvz seems to experience.

**Comment by aliostad** [comment]
Thank you, I am so sorry @joostvz . This issue was missed. 
Thanks @kpstolk yes the fix is easy. I will get this sorted.

**Comment by aliostad** [comment]
Hi, issue is fixed in version 1.2.3.
Sorry for the long delay. Spreading myself too thin has taken its toll.

**Comment by joostvz** [comment]
@aliostad No problem, thanks for fixing!
