### ISSUE TITLE
How to use CacheCow Server when data is sourced externally...

### ISSUE THREAD

**Issue by arasheedu** [aliostad/CacheCow#170]
Hi,

My API controller fetches data from external data source and serves up only GET requests (parameterized). How to efficiently use CacheCow server in such a scenario?

Ideally:
I should initiate a request to an external source (these are MDX queries formed based on parameters passed to the GET API) and invalidate the cached result when the request comes through.

Any samples for such a scenario?

Please advice

Thanks,
Rasheed

**Comment by aliostad** [comment]
Hi,

You can call InvalidateRoutePattern, etc to invalidate when you change your data. It is not ideal and in the next version it will work based on the data to return.

Cheers
Ali
