### ISSUE TITLE
I've implemented step by step CacheCow .Why cache does not work?

### ISSUE THREAD

**Issue by behrouzmoslem** [aliostad/CacheCow#171]
I've implemented step by step cacheCow with the help resources.But every time the postman send requests, refer the request to Sql Server. what is the problem?
I asked my question in stackoverflow Please reply.
http://stackoverflow.com/questions/41675841/ive-implemented-step-by-step-cachecow-why-cache-does-not-work

**Comment by aliostad** [comment]
Hi,

First of all I highly suggest not to use SQL Server for storage. Ideally Redis should be used or perhaps memcached.

Second, I cannot see any part of your code setting up CachingHandler? Where is that code?

**Comment by behrouzmoslem** [comment]
hi, I used this Code in Register method
` var connString = "Data Source=.;Initial Catalog=testdb;...";
            var eTagStore = new CacheCow.Server.EntityTagStore.SqlServer.SqlServerEntityTagStore(connString);
            GlobalConfiguration.Configuration.MessageHandlers.Add(new CachingHandler(GlobalConfiguration.Configuration, eTagStore));
`
I am working in a health center. Where there are high transaction information. From the beginning of Sql Server is used. I am not allowed to change it.
In programming API, requires the use of Cache system that is synchronized with the server Destributed and LazyLoading to support.

**Comment by aliostad** [comment]
Did you create tables required for it? There is a script in the nuget package to generate tables and you need to run it.

Frankly I do not support SQL CacheCow anymore and suggest you get an ephemeral cache and that would be fully supported.

**Comment by behrouzmoslem** [comment]
yes,I run it.
thanks

**Comment by aliostad** [comment]
Sorry I noticed you closed it. Did you get your problem fixed? When I said not supported did not mean I will not help you! I meant if it comes to it that there is a problem inside the CacheCow itself then my hand is tight. I believe at this stage it should work for you and I am more than happy to help you get it going.

**Comment by aliostad** [comment]
No response. Closing.
