### ISSUE TITLE
Purging of CacheState stale records?

### ISSUE THREAD

**Issue by jagbarcelo** [aliostad/CacheCow#174]
We've been using CacheCow for sometime in our Project and we have noticed that the table CacheState has been constantly growing. Now it has records as old as of March 2016 (LastModified column).

Does this make any sense? Doesn't CacheCow delete its own records once they become old beyond a configurable amount of time?

Thanks.

**Comment by aliostad** [comment]
Hi, what storage are you using? Is it SQL?

**Comment by aliostad** [comment]
No response. Closing.

**Comment by jagbarcelo** [comment]
Sorry for the delay. Yes we're using SQL as storage.

**Comment by aliostad** [comment]
Yes, CacheCow does not clear old entries - it has no mechanism to do it. So you need to set up jobs to delete old entries.

I generally recommend not to use SQL Server for caching - but if it works well for you then fine.
