### ISSUE TITLE
Null reference exception if the response is null in ContentHashETagAttribute

### ISSUE THREAD

**Issue by TMiNus** [aliostad/CacheCow#178]
The following lines produce a null reference exception in ContentHashETagAttribute if the ```Response``` from ```actionExecutedContext``` is null

 ```
base.OnActionExecuted(actionExecutedContext)
if (actionExecutedContext.Response.Content == null)
      return;
```

**Comment by aliostad** [comment]
C# 6 is not supported can you please provide C# 5?

**Comment by TMiNus** [comment]
#119 has this same code in C# 5. The errors in that pull request are not related at all with the changes made in the pull request.

**Comment by aliostad** [comment]
Do you mind sending instead of #119 ?
