### ISSUE TITLE
RedisEntityTagStore, why we need different keys for Etag, Uri and Pattern?

### ISSUE THREAD

**Issue by flowdopip** [aliostad/CacheCow#180]
public void AddOrUpdate(CacheKey key, TimedEntityTagHeaderValue eTag)
        {
            _database.StringSet(key.HashBase64, eTag.ToString(), _expiry);

            // resource
            var resourceKey = string.Format(ResourceFormat, key.ResourceUri);
            _database.SetAdd(resourceKey, key.HashBase64);
            if (_expiry.HasValue)
                _database.KeyExpire(resourceKey, _expiry);

            // routePattern
            var routePatternKey = string.Format(RoutePatternFormat, key.RoutePattern);
            _database.SetAdd(routePatternKey, key.HashBase64);
            if (_expiry.HasValue)
                _database.KeyExpire(routePatternKey, _expiry);

        }

this is a behavior of redis? something to improve performance?

**Comment by aliostad** [comment]
Sorry, what exactly you mean is the behaviour of Redis? Can you please elaborate, what specifically?

App we are doing here is to store the data and if there is expiry, set that on the key. I cannot see anything strange here.
