### ISSUE TITLE
Using CacheCow.Server.EntityTagStore.SqlServer without having eTag from Client (Question)

### ISSUE THREAD

**Issue by invit-dvd** [aliostad/CacheCow#181]
Hi.

I just installed and started using CacheCow and finds it really easy to setup, I do have a question regarding the eTags which I´m not sure is supported. 

The problem I have is that our data is very heavy and the caching really helps here so I would like the data to be pre cached as much as possible. We only have a couple of web api urls that the user can access the data but some of them have a lot of different query parameters so the url differs a lot. When a request comes in a heavy calculation is made.  All of the requests the users do are HttpGet.

My question is, can I in some way use cache cow to find the right cache by the route instead of an etag, because from what I understand, the request must contain the etag so that the server knows which cache to use, but that dosen´t work when different, new users, visits the site and performs the same url request? Maybe I´ve missed something but I can´t find any information about this.

Best Regards
/David

**Comment by aliostad** [comment]
Hi David,

I am pleased you have found CacheCow useful.

CacheCow makes sure the eTag for the URL is the same regardless but by default it uses an in-memory store to lookup the value of eTag and if you have a server farm (more than a single server) then it would not work as each server gets its own eTag. So you would want to use a central storage for storing this eTag and that is where many storage mechanisms supported such as Redis, Memcached, SQL Server, etc.

By default a route has a single eTag associated with it - these get multiplied by the variance you define using Vary headers, e.g. if you say vary cache by Accept-Language then for each parameter you get one eTag, etc.

Hope this helps, if you explain a bit more I should be able to help.
