### ISSUE TITLE
I am not able make CacheCow.Client working for me

### ISSUE THREAD

**Issue by himadric** [aliostad/CacheCow#182]
Hi,
I am using this library first time. I must be doing something wrong or the API Caching implemented using CacheCow needs some modification . It never returns 304. Also, I don't see anything related to Cache in the request header. The Caching for the API does work when call are made from the browser. Thanks for your time.

**Below is code I wrote. It's pretty much the code I copied from your blog.**
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using CacheCow.Client;
using CacheCow.Client.Headers;

namespace CacheTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var client = new HttpClient(new CachingHandler()
            {
                InnerHandler = new HttpClientHandler()
            } );
            var initialResponse = client.GetAsync(
                  "http://insitecommerce.local.com/api/v1/categories?startCategoryId=null&maxDepth=2").Result;
            var initialResponseHeader = initialResponse.Headers.Single(
                   x => x.Key == CacheCowHeader.Name).Value.First();
            Console.WriteLine(initialResponse.Headers.ETag.Tag);
            Console.WriteLine(initialResponseHeader);

            Console.ReadLine();

            var secondResponse = client.GetAsync("http://insitecommerce.local.com/api/v1/categories?startCategoryId=null&maxDepth=2").Result;
            var secondResponseHeader = secondResponse.Headers.Single(
                  x => x.Key == CacheCowHeader.Name).Value.First();
            Console.WriteLine(secondResponse.Headers.ETag.Tag);
            Console.WriteLine(secondResponseHeader);

            Console.ReadLine();

            var thirdResponse = client.GetAsync("http://insitecommerce.local.com/api/v1/categories?startCategoryId=null&maxDepth=2").Result;
            var thirdResponseHeader = thirdResponse.Headers.Single(
                  x => x.Key == CacheCowHeader.Name).Value.First();
            Console.WriteLine(thirdResponse.Headers.ETag.Tag);
            Console.WriteLine(thirdResponseHeader);

            Console.ReadLine();

            var fourthResponse = client.GetAsync("http://insitecommerce.local.com/api/v1/categories?startCategoryId=null&maxDepth=2").Result;
            var fourthResponseHeader = fourthResponse.Headers.Single(
                  x => x.Key == CacheCowHeader.Name).Value.First();
            Console.WriteLine(fourthResponse.Headers.ETag.Tag);
            Console.WriteLine(fourthResponseHeader);

            Console.ReadLine();
        }
    }
}
`
**Output in the console**
"2c4360e58e5c4d889f0b1cba3c9dc729"
1.3.0.0;not-cacheable=true;did-not-exist=true

"3146215bd0f946a69d1605e1156983d3"
1.3.0.0;not-cacheable=true;did-not-exist=true

"3146215bd0f946a69d1605e1156983d3"
1.3.0.0;not-cacheable=true;did-not-exist=true

"3146215bd0f946a69d1605e1156983d3"
1.3.0.0;not-cacheable=true;did-not-exist=true

**First Request header in Fiddler**
GET /api/v1/categories?startCategoryId=null&maxDepth=2 HTTP/1.1
Host: insitecommerce.local.com
Connection: Keep-Alive

**First Response Header in Fiddler**
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: application/json; charset=utf-8
Last-Modified: Sun, 28 May 2017 15:22:37 GMT
ETag: W/"2c4360e58e5c4d889f0b1cba3c9dc729"
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
Set-Cookie: InsiteCacheId=880be19a-019a-4e31-b03a-cb33e6ad37df; path=/
Set-Cookie: CurrentLanguageId=a26095ef-c714-e311-ba31-d43d7e4e88b2; expires=Tue, 27-Jun-2017 15:22:37 GMT; path=/
Set-Cookie: SetContextLanguageCode=en-us; expires=Tue, 27-Jun-2017 15:22:37 GMT; path=/
X-ServerTime: 55
X-Powered-By: ASP.NET
p3p: policyref="/w3c/privacy.htm", CP="NOI DSP COR NOR UNI STA"
Date: Sun, 28 May 2017 15:22:37 GMT
Content-Length: 5308

**Second Request Header in Fiddler**
GET /api/v1/categories?startCategoryId=null&maxDepth=2 HTTP/1.1
Host: insitecommerce.local.com
Cookie: InsiteCacheId=880be19a-019a-4e31-b03a-cb33e6ad37df; CurrentLanguageId=a26095ef-c714-e311-ba31-d43d7e4e88b2; SetContextLanguageCode=en-us

**Second Response Header in Fiddler**
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: application/json; charset=utf-8
Last-Modified: Sun, 28 May 2017 15:22:39 GMT
ETag: W/"3146215bd0f946a69d1605e1156983d3"
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
Set-Cookie: CurrentLanguageId=a26095ef-c714-e311-ba31-d43d7e4e88b2; expires=Tue, 27-Jun-2017 15:22:39 GMT; path=/
Set-Cookie: SetContextLanguageCode=en-us; expires=Tue, 27-Jun-2017 15:22:39 GMT; path=/
X-ServerTime: 16
X-Powered-By: ASP.NET
p3p: policyref="/w3c/privacy.htm", CP="NOI DSP COR NOR UNI STA"
Date: Sun, 28 May 2017 15:22:39 GMT
Content-Length: 5308

**Third Request Header in Fiddler**
GET /api/v1/categories?startCategoryId=null&maxDepth=2 HTTP/1.1
Host: insitecommerce.local.com
Cookie: InsiteCacheId=880be19a-019a-4e31-b03a-cb33e6ad37df; CurrentLanguageId=a26095ef-c714-e311-ba31-d43d7e4e88b2; SetContextLanguageCode=en-us

**Third Response Header in Fiddler**
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: application/json; charset=utf-8
Last-Modified: Sun, 28 May 2017 15:22:39 GMT
ETag: "3146215bd0f946a69d1605e1156983d3"
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
Set-Cookie: CurrentLanguageId=a26095ef-c714-e311-ba31-d43d7e4e88b2; expires=Tue, 27-Jun-2017 15:22:41 GMT; path=/
Set-Cookie: SetContextLanguageCode=en-us; expires=Tue, 27-Jun-2017 15:22:41 GMT; path=/
X-ServerTime: 15
X-Powered-By: ASP.NET
p3p: policyref="/w3c/privacy.htm", CP="NOI DSP COR NOR UNI STA"
Date: Sun, 28 May 2017 15:22:41 GMT
Content-Length: 5308

**Comment by aliostad** [comment]
Sorry for the delay in responding. 
If you notice you will find that the date of the request and expiry are the same (dates highlighted by <<< and >>>)

```
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: application/json; charset=utf-8
Last-Modified: Sun, 28 May 2017 15:22:39 GMT
ETag: "3146215bd0f946a69d1605e1156983d3"
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
Set-Cookie: CurrentLanguageId=a26095ef-c714-e311-ba31-d43d7e4e88b2; expires=Tue, 27-Jun-2017 15:22:41 GMT; path=/
Set-Cookie: SetContextLanguageCode=en-us; expires=<<<Tue, 27-Jun-2017 15:22:41 GMT>>; path=/
X-ServerTime: 15
X-Powered-By: ASP.NET
p3p: policyref="/w3c/privacy.htm", CP="NOI DSP COR NOR UNI STA"
Date: <<<Sun, 28 May 2017 15:22:41 GMT>>>
Content-Length: 5308
```

By default expiry is zero and you need to set it. This blog post provides information on that:
[http://byterot.blogspot.co.uk/2013/03/rest-asp-net-wep-api-0.4-new-features-breaking-change-cachecow-server.html](http://byterot.blogspot.co.uk/2013/03/rest-asp-net-wep-api-0.4-new-features-breaking-change-cachecow-server.html)
