### ISSUE TITLE
CacheCow Client goes down in case of highloading.

### ISSUE THREAD

**Issue by studenikin** [aliostad/CacheCow#184]
We tried to highload CacheCow Client and it became unresponsible for some period of time:
 
The code:
 
```
public class MyClient
{
    private readonly HttpClient _client;
 
    public MyClient(ICacheStore cacheStore)
    {
        _client = new HttpClient(new CachingHandler(cacheStore)
        {
            InnerHandler = new HttpClientHandler()
        });
    }
 
    public async string GetProducts()
    {
        using (var response = await _client.SendAsync("http://mydomain.com/products"))
        {
            return await response.Content.ReadAsStringAsync();
        }
    }
}
```
![cachecow](https://user-images.githubusercontent.com/1820031/27507760-b902548e-58de-11e7-95c8-7a218cd80bb9.png)

When we droped CacheCow Client everything started working fine:
 
The code:
```
public class MyClient
{
    private readonly HttpClient _client;
 
    public MyClient(ICacheStore cacheStore)
    {
        _client = new HttpClient();
    }
 
    public async string GetProducts()
    {
        using (var response = await _client.SendAsync("http://mydomain.com/products"))
        {
            return await response.Content.ReadAsStringAsync();
        }
    }
}
```
![nocachecow](https://user-images.githubusercontent.com/1820031/27507769-f512f212-58de-11e7-82b3-a8b81ed0f6ca.png)

**Comment by aliostad** [comment]
Hi, thanks for using and then also reporting the issue. So may I ask what storage are you using? Do you have a repro?

**Comment by studenikin** [comment]
Hi! We use RedisStore. Not sure what repro is... did you mean source code?

**Comment by aliostad** [comment]
OK then, can you please use https://www.nuget.org/packages/CacheCow.Client45/ nuget package instead of the original?

The original code was written to support .NET 4.0 and async/await code had to be written with so many hoops. So this one is re-written with async-await and I believe will fix your issue.

Look forward to hear back from you.

**Comment by studenikin** [comment]
Thanks for quick answer! We'll give it a try, and I'll get back to you with feedback.

**Comment by aliostad** [comment]
@studenikin bear in mind this says alpha but I have been using it in production for a year. It is rock solid and I will publish v1.0.0 just now.

**Comment by aliostad** [comment]
@studenikin OK just published final packages. Please also use the corresponding Redis package: https://www.nuget.org/packages/CacheCow.Client.RedisCacheStore45/1.0.0

**Comment by studenikin** [comment]
@aliostad We've just performed tests against new packages and...the result is great! Everything works fine and stable. Hereby I'm closing the issue.

**Comment by aliostad** [comment]
Oh thank you so much! Would be great to see a report from you, hopefully a blog post or something - I doubt anyone used it under this huge load
