### ISSUE TITLE
Using EntityTagStore.SqlServer with CacheCow.Server45

### ISSUE THREAD

**Issue by ianrathbone** [aliostad/CacheCow#186]
Hi, EntityTagStore.SqlServer has a nuget dependency on CacheCow.Server - what is the recommended practice to move over to using CacheCow.Server45?

**Comment by aliostad** [comment]
Hi Ian,

The plan is to move everything in the end to `CacheCore`. I was hoping this could be already possible with .NET Standard 2.0 but previews still a bit flaky - having said that I will start working on it pretty soon. 

The issue we had and reason for 45 was that since CacheCow was .NET 4.0, we had mixture of sync and async which at high load caused problems. I have got rid of them now but the SQL one not implemented. Are you interested in SQL?

**Comment by ianrathbone** [comment]
Understood! Yes very interested in SQL as we are using it in a production environment and would like to switch over to the 45 version if possible.

**Comment by aliostad** [comment]
Sure, I will get on to that. Hopefully will be done by the end of this week.

**Comment by aliostad** [comment]
Hi @ianrathbone 

The alpha version is available for test on nuget:
**CacheCow.Server.EntityTagStore.SqlServer45 version 1.1.0-alpha1**

Obviously you need to use `install-package CacheCow.Server.EntityTagStore.SqlServer45 -pre` to bring pre-release packages.

Also make sure you modify your connection string so `async` read/write can be used.

**Comment by aliostad** [comment]
Hi @ianrathbone I hope you can get some time to look into this. Since you are the only user at the mo, I can only change from alpha to stable when you are happy.

**Comment by ianrathbone** [comment]
Hi @aliostad I'm looking to integrate and test this week - thank you very much for making the effort!

**Comment by ianrathbone** [comment]
Hi @aliostad seeing the following error:

> Method 'TryGetValue' in type 'CacheCow.Server.EntityTagStore.SqlServer.SqlServerEntityTagStore' from assembly 'CacheCow.Server.EntityTagStore.SqlServer, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by aliostad** [comment]
Thanks let me look into it.

**Comment by aliostad** [comment]
I see, my nuget package is dependent on `CacheCow.Server` not `CacheCow.Server45`. OK I am releasing alpha2.

Please have a look when you can.

Cheers

**Comment by ianrathbone** [comment]
@aliostad just wanted to say thank you for this I've finally gotten it into production and it works well :)

**Comment by aliostad** [comment]
Made my day! Thanks.
