### ISSUE TITLE
ContentHashETagAttribute returns a 500 if a response is an error

### ISSUE THREAD

**Issue by pelavall** [aliostad/CacheCow#193]
If ContentHashETagAttribute is in the response pipeline and an error (404, 400, 503) is returned, ContentHashETagAttribute will fail and return a 500 rather than preserving the original error.

**Comment by pelavall** [comment]
On an exception Response is null.

**Comment by aliostad** [comment]
Hi, sorry for late reply.

ContentHashEtag is work in progress and I guess this has not been made known.  In fact, I explain here [that](http://byterot.blogspot.co.uk/2017/04/Future-CacheCow-birth-CacheCore-REST-HTTP-dotnetcore-middleware-caching-conditional-put-get.html) server side of the cachecow probably will not be ported to .NET Core.

**Comment by pelavall** [comment]
👌

**Comment by grisha0088** [comment]
I'm sorry for offtop, but could you please explain or give me example how to use ContentHashETagAttribute?
I marked my controller method by this attribute [ContentHashETag] but nothing happened - there is no "x-cachecow-content-hash-md5" header in responce.

**Comment by aliostad** [comment]
Well, you hit it on the nail. That is the problem: the idea was good but not really useful in the old ASP.NET. IN .NET core it will be easier to do hence CacheCore project will change the direction of server side caching.
