### ISSUE TITLE
Modefication of data when i enter 

### ISSUE THREAD

**Issue by bharathpbk** [aliostad/CacheCow#194]
I have a GET method which returns data. For first time I called and its 200 Ok. Then i have modified the data in one post method. Now i am calling the same Get. Now it's returning 304 Not Modified. It supposed to be return 200 OK. How to modify the cache using ETag, in that case?

**Comment by aliostad** [comment]
That is correct. However, without knowing your path structure I cannot comment.

Normally, if you call 
`GET /blah/123`

And then calll

`POST /blah/123`

It should work. But if you are using attribute routing and you have come up with creative routing then CacheCow would not know. Hence can you please explain your routing?
