### ISSUE TITLE
No Async Support

### ISSUE THREAD

**Issue by jsangari-ssat** [aliostad/CacheCow#195]
Hi,

Looking to Use your framework for Cache Handling, Our API's are all Async but I see that Your Interfaces (ICacheStore,IEntityTagStore ) and Classes are All Sync . For data Sources that expose async methods (Like RedisCache) this will mount to doing Task.Factory.StartNew which will be highly inefficient, Is there a desire to add Async Methods here?

**Comment by aliostad** [comment]
Hi,

I suggest you .NET 4.5 libraries which have async support.
They all have 45 at the end of the nuget package for example:
https://www.nuget.org/packages/CacheCow.Client45/

We are using them in production for more than a year.
