### ISSUE TITLE
What is the status of the .NET 4.5 packages?

### ISSUE THREAD

**Issue by joostvz** [aliostad/CacheCow#199]
Hi Ali,

In the Readme you state that it is prefered to use the .NET 4.5 version of the NuGet packages. But for me it is quite unclear what the differences are with the 'normal' version of the packages. One thing I noted is that my previous issue ( #168) is only fixed on master, not on the dotnet45 branch.

So do you have plans to merge master into the dotnet45 branch? Or vice versa, and ditch the older version? According to [Wikipedia ](https://en.wikipedia.org/wiki/.NET_Framework_version_history#Overview) .NET 4.5 was released almost 6 years ago, so should you still support older .NET versions?

**Comment by aliostad** [comment]
Hi,

the normal packages were developed when .NET 4.0 and just before 4.5 was out and CacheCow was committed to keep supporting .NET 4.0 hence unfortunately some sync/async concepts got mixed and under high performance resulted in locks and rarely deadlocks (although they do happen).

So you should only use 45 packages. Having said that, I am working on the next version CacheCow which will replace existing and would be fully async - It will also support .NET Core. Timeline is around a couple of weeks hopefully.

Does that answer your question?

**Comment by joostvz** [comment]
Nice that you're working on the next version with .NET Core support! We'll definitely be using that version when it's finished.

But in the meantime, will the 4.5 packages contain all fixes that were done in the 4.0 packages? I don't see any merges between the two branches (other than the _supamerge_ branch).

**Comment by joostvz** [comment]
We're using the client library, so that should be no problem to update to the 4.5 library. We'll await the supa merge.

Thanks for the update!

**Comment by aliostad** [comment]
OK I am closing the issue.
