### ISSUE TITLE
cannot get CacheControlPolicty to work

### ISSUE THREAD

**Issue by AmaelN** [aliostad/CacheCow#202]
On a controller that I don't want data to be cached, i've set the following attribute on the controller

    ```
    [HttpCacheRefreshPolicy(0)]
    [HttpCacheControlPolicy(true, 0, true,true,false,true)]
```
The data is still cached and return an http code 304 with previous data even after I update it. 
I'm trying to update an image (the image is updated on the server) nevertheless redis is returning the old one even if it is not supposed to cache it.

Any suggestions ?

**Comment by aliostad** [comment]
Sorry I missed this one. Which version are you using?

**Comment by AmaelN** [comment]
I will wait for the new cache core....

**Comment by aliostad** [comment]
The beta 2.0.0 is released, can you have a look?

**Comment by AmaelN** [comment]
Thanks,
I will test it and try to use it during the week of 7-10 of May which is my
next available time.

**Comment by aliostad** [comment]
Ah... by that time the new CacheCow will be released. Anyhow, whenever have questions or need help on this let me know.
