### ISSUE TITLE
Disabling cache on specific action methods

### ISSUE THREAD

**Issue by dungtrandk** [aliostad/CacheCow#203]
Below is my code in WebApiConfig.cs where I setup the cachecow cache:

            // Create cache store that handles all persistence of cache to a store.
            // In this case we use SQL as the store.
            var cacheStore = new SqlServerEntityTagStore(connectionString);

            // Create cache handler that handles all incoming requests and makes sure
            // to cache it appropriately according to chaching policies.
            var cacheHandler = new CachingHandler(config, cacheStore);

            cacheHandler.CacheControlHeaderProvider = new AttributeBasedCacheControlPolicy(
                new CacheControlHeaderValue()
                {
                    NoCache = true,
                    NoStore = false
                }).GetCacheControl;

            // Sets an overall refresh interval on all cached controllers and action methods.
            // Refresh interval is stored in appsettings
            var apiRefreshInterval = int.Parse(ConfigurationManager.AppSettings["ApiRefreshInterval"]);
            cacheHandler.CacheRefreshPolicyProvider = new AttributeBasedCacheRefreshPolicy(
                TimeSpan.FromSeconds(apiRefreshInterval)).GetCacheRefreshPolicy;

And on action methods that i use caching, i add this attribute:

_[HttpCacheRefreshPolicy("SomeInterval")]_

And all of this works great.

But I need a way to specify that a specific action method wil be prevented from adding a row to the SqlServerEntityTagStore.

Right now all of my action methods are creating a row in the SqlServerEntityTagStore (SQL Server) and this causes the action methods to return a 304 (After the first call) due to the cached ETag.

Is there a way of NOT adding a row in the SqlServerEntityTagStore (SQL Server) for specific action methods?

**Comment by aliostad** [comment]
Hi,

CacheCow 2.0.0-preview is out and in that you would not even need a SQL Server. I am literally updating the docs (part done) to release 2.0.0.0 within days. Would you give that a go? There are docs and sample projects.

If this is already in production and cannot use 2.0.0.0 let me know please.

**Comment by dungtrandk** [comment]
Hi again

I just downloaded the cachecow.common version 2 preview and it seems like the new lib is missing the IEntityTagStore used by the CachingHandler.

I get this error when running the new version:

Could not load type 'CacheCow.Common.IEntityTagStore' from assembly 'CacheCow.Common, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.

Line 54:             // Create cache handler that handles all incoming requests and makes sure
Line 55:             // to cache it appropriately according to chaching policies.
_**Line 56:             var cacheHandler = new CachingHandler(config);**_
Line 57: 
Line 58:             cacheHandler.CacheControlHeaderProvider = new AttributeBasedCacheControlPolicy(


[TypeLoadException: Could not load type 'CacheCow.Common.IEntityTagStore' from assembly 'CacheCow.Common, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.]    CacheCow.Server.CachingHandler..ctor(HttpConfiguration configuration, String[] varyByHeader) +0    AMEssentials.Api.WebApiConfig.RegisterCacheHandlers(HttpConfiguration config) in C:\Users\dt\Documents\Visual Studio 15\Projects\AMEssentials.Web\AMEssentials.Api\App_Start\WebApiConfig.cs:56    AMEssentials.Api.WebApiConfig.Register(HttpConfiguration config) in C:\Users\dt\Documents\Visual Studio 15\Projects\AMEssentials.Web\AMEssentials.Api\App_Start\WebApiConfig.cs:24    System.Web.Http.GlobalConfiguration.Configure(Action`1 configurationCallback) +27    AMEssentials.Api.WebApiApplication.Application_Start() in C:\Users\dt\Documents\Visual Studio 15\Projects\AMEssentials.Web\AMEssentials.Api\Global.asax.cs:14
--




As you can see I dropped the CacheStore of type SqlServerEntityTagStore cause this was giving an compile time error.

Please let me know what I am missing or doing wrong.

Thanks!

**Comment by aliostad** [comment]
CachingHandler is no more, you need to use a filter. You probably are still using the old library or a mix. The best way probably is to look at the Web API samples after you clone the github project.

**Comment by dungtrandk** [comment]
So what you are saying is that 

1: You cannot cache to SQL server anymore out-of-the-box?

2: If you would like to cache to SQL server then add a filter and add cache-to-sql-server code in this filter? 

Thanks

**Comment by dungtrandk** [comment]
Many of my action methods are executing big SQL queries to get the data.
It is these action methods that I would like to cache.

Now, when I was using the IEntityTagStore to add these entries to an SQL server it stored the etags and other metadata PLUS a binary field as well. As I understood it this field was the cache, right?

So the reason I would like to persist the cache in SQL is that I dont want these big SQL queries to re-cache each time I restart my Web Api (this is assuming it caches to the memory).

Thats why I would like to persist my cache data in SQL.

Please, if you could further explain to me or show me how I can keep doing it this way, I would be thankful.

**Comment by aliostad** [comment]
In HTTP caching, data actually gets cached on the client (not the server). Have a read [here].(https://github.com/aliostad/CacheCow/blob/master/README.md#concepts-and-definitions).

But CacheCow provides means to reduce pressure on your back-end.

**Comment by dungtrandk** [comment]
Due to security requirements i am not able to cache on clients. Will/is it still possible to cache on sql with version 2?

**Comment by aliostad** [comment]
Then I suggest HTTP Caching (and hence neither CacheCow version 1.x or 2.0) not suitable for you.
You could try Output Cache From Filip Woj:

https://github.com/filipw/Strathweb.CacheOutput
