### ISSUE TITLE
Support RestSharp

### ISSUE THREAD

**Issue by shykln** [aliostad/CacheCow#204]
Hi Alistad,

I want to ask if CacheCow can work with RestSharp. If it can, how should I use it? Thanks!

**Comment by aliostad** [comment]
Hi Damian,

I am afraid, short answer is no. RestSharp is not supported and currently there is no plan to support it - this was done before .NET's HttpClient and from that little I know about it, HttpClient provides richer abstractions and I remember John Sheehan its author even say its Best Before time has passed.

But anyhow, you are free to use it if it solves the problem and I could consider accepting PR for adding PostSharp but at this point not a priority for me.
