### ISSUE TITLE
Decorate HttpDelete and/or HttpPatch with HttpCacheFactory

### ISSUE THREAD

**Issue by ahedreville** [aliostad/CacheCow#207]
Hi Thanks a lot for this library for net core.
However I have some question
It is possible to decorate  `[HttpDelete]` and/or `[HttpPatch]` with i.e. `[HttpCacheFactory(0, ViewModelType = typeof(Car))]` ?
and have short-circuit the controller action with 412 Precondition Failed like it does for  [HttpPut] with an If-Match eTag Header value?
If not implement. Can some how can it be implemented?
I guess that I would to create a new, modified or derived `HttpCacheFactoryAttribute`

**Comment by aliostad** [comment]
Hi @ahedreville this would be just some code change and releasing the next version. I should be able to deliver this in the next few days.

**Comment by aliostad** [comment]
Hi,

This is now implemented in v2.3.0. All you need to do, is to decorate the DELETE or PATCH actions with CacheCow's attribute. Also now, CacheCow.Client validates DELETE and PATCH calls.

Samples have been updated, you can check those to see them in action.

**Comment by ahedreville** [comment]
Thanks I lot.
Tested on my net core app and works like charm!!

**Comment by aliostad** [comment]
Awesome! The fuzzy feeling of seeing someone's problem being solved... that is why I do it.
Thanks for making CacheCow better.
