### ISSUE TITLE
MustRevalidate

### ISSUE THREAD

**Issue by sag3ll0** [aliostad/CacheCow#210]
How i can set MustRevalidate value? Now by default after time expired its responce 304 code

**Comment by aliostad** [comment]
MustRevalidate means the cache proxy or client MUST revalidate the stale resource and cannot use it anymore *after* expiry. 

Do you need the client to always revalidate?

**Comment by sag3ll0** [comment]
Yes, the fact is that now, together with the code 304, a full-fledged payload is returned (and the request time becomes large)

**Comment by sag3ll0** [comment]
on image first request is fulltime (full load)
2nd request with 200(cache)
and 3 request with 304 take time almost as fulltime
![image](https://user-images.githubusercontent.com/18505406/43739534-1a1dadde-99d1-11e8-9f75-dbd27b7d6ceb.png)

**Comment by sag3ll0** [comment]
How I can avoid execute controller action when data is not changed?

**Comment by aliostad** [comment]
3rd request does not return the whole response, only the fact that it has not changed. Have you read the docs? There are extensive information on [optimising this](https://github.com/aliostad/CacheCow#cachecowserver-advanced-options) and also I have published a blog [post](http://byterot.blogspot.com/2018/06/cachecowserver-20-using-it-on-aspnetcoremvc-dotnetcore-etag-http-caching-aspnetcore.html) on it.
