### ISSUE TITLE
Question: ICacheResource minimal implementation

### ISSUE THREAD

**Issue by sag3ll0** [aliostad/CacheCow#211]
Hi, I try implement ICacheResource
```
public abstract class BaseDto: ICacheResource
    {
        [Key]
        public virtual long? Id { get; set; }

        public virtual string CreatedBy { get; set; }
        public virtual string ModifiedBy { get; set; }
        public virtual DateTime? CreatedDate { get; set; }
        public virtual DateTime? ModifiedDate { get; set; }

        public BaseDto(){}

        public BaseDto(BaseEntity entity)
        {
            Id = entity.Id;
            CreatedBy = entity.CreatedBy;
            ModifiedBy = entity.ModifiedBy;
            CreatedDate = entity.CreatedDate;
            ModifiedDate = entity.ModifiedDate;
        }

        public TimedEntityTagHeaderValue GetTimedETag()
        {
            return new TimedEntityTagHeaderValue(new DateTimeOffset(ModifiedDate.Value));
        }
    }
```
But i don't understand what need to next. I use Autofac as DI.
BaseDto is base class for CarDto and PlaneDto (i don't want write GetTimedETag in each chield class, becouse it will be same).

**Comment by aliostad** [comment]
Nothing, it will just work. This will prevent the key to be generated by serialisation. However, your backend will still be called and the item need to be read from your data store.

If you want to protect your backend, you need to implemented your own `ITimedETagQueryProvider` to check with database whether an item has changed or not.

**Comment by sag3ll0** [comment]
Thanks for response. I try debug generate etag by implementing ICacheResource, and this not execute method GetTimedETag in baseDto.

**Comment by aliostad** [comment]
Does not?? If it does not it could be a bug.

If you are using default extractor, this is the line where it extracts the ETag:
https://github.com/aliostad/CacheCow/blob/master/src/CacheCow.Server/ETag/DefaultTimedETagExtractor.cs#L25

**Comment by sag3ll0** [comment]
Maybe is not bug, maybe i don add somewhere something, I use webapi 2, with autofac.

**Comment by sag3ll0** [comment]
for work GetTimedETag need add  ViewModelType in attribute?
[HttpCache(DefaultExpirySeconds = 0, ViewModelType = typeof(Car))]

**Comment by aliostad** [comment]
Not really if you are not providing your own extractor.

**Comment by aliostad** [comment]
what was the problem??

**Comment by aliostad** [comment]
@sag3ll0 can you please explain what the problem was? This helps others that might experience your problem. Thanks
