### ISSUE TITLE
Add editorconfig file

### ISSUE THREAD

**Issue by zhofre** [aliostad/CacheCow#215]
Can we add an editorconfig file to support contributors in maintaining a consistent code style?

Reference: https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2017

**Comment by aliostad** [comment]
Thank you. Feel free to send a PR.

**Comment by zhofre** [comment]
OK, I'll add it and send a PR with the initial version. We can discuss the severity of warnings and what to do with current inconsistencies as part of PR.
