### ISSUE TITLE
Not responding 412 when ETag doesnt match on PUT request

### ISSUE THREAD

**Issue by gabolarraguivel** [aliostad/CacheCow#221]
When making a PUT request with an ETag value on the If-Match header, cachecow is not responding 412 Precondition Failed on Web Api 2.

This issue is on the web api 2 samples too.

**Comment by aliostad** [comment]
Hi I checkout the samples and the problem was the dependency injection. If you check the `.WebApi.WithQueryAndIoc` sample, it does send back 412 error.

**Comment by gabolarraguivel** [comment]
I already tested it and it doesn't work. 
I did what you say on the Readme:

C, C, C to add a few cars and then L, O, U to see an unsuccessful HTTP PUT/PATCH/DELETE validation resulting in status 412

And even with .WebApi.WithQueryAndIoc it doesn't result in a 412 error.

Have you tested it like I did?

**Comment by aliostad** [comment]
I updated the code, did you pull again?

**Comment by aliostad** [comment]
If you do not get back to me I have to close the issue.

**Comment by gabolarraguivel** [comment]
Yeah now its working. Thank you
