### ISSUE TITLE
Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property

### ISSUE THREAD

**Issue by jagbarcelo** [aliostad/CacheCow#223]
I have a WebApi project where CacheCow.Server is used for caching EntityFramework responses (usually Json objects taken from a database). Due to the parent-child relationships and circular referencing loops of System.Data.Entity.DynamicProxies, we get this exception for some of our published API methods:

`Excepción producida: 'Newtonsoft.Json.JsonSerializationException' en mscorlib.dll
Error de conexión en WebApiSiteAssembly.Attributes.HandleApplicationExceptionsAttribute.OnException: Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'Group' with type 'System.Data.Entity.DynamicProxies.Group_58148824D915E126EAB1B78FC3443C90AE50FB12F4254FBF524A3C7D29E323D2'. Path '[5].ProjectSummaries[0]'.
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   en Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   en Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   en CacheCow.Server.JsonSerialiser.Serialise(Object o)
   en CacheCow.Server.DefaultTimedETagExtractor.Extract(Object viewModel)
   en CacheCow.Server.DefaultCacheDirectiveProvider.Extract(Object viewModel)
   en CacheCow.Server.WebApi.HttpCacheAttribute.<OnActionExecutedAsync>d__5.MoveNext()
`

The fix is quite straightforward, in CacheCow.Server.JsonSerialiser, just change the original `return Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(o))` with this:

~~~~
      JsonSerializerSettings settings = new JsonSerializerSettings()
      {
          ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore,
          PreserveReferencesHandling = Newtonsoft.Json.PreserveReferencesHandling.Objects
      };

      return Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(o, settings));
~~~~

**Comment by aliostad** [comment]
HI,

I had a look. Doing this is very specific to your use-case and I am sure some other users could have different use cases.

As a library, CacheCow should allow you to modify its behaviour to suit your need. As you can see, I register `JsonSerialiser` as the default but you can **replace** that type with yours including those aspects - just implement a simple interface.

If you need help on that please let me know.

**Comment by jagbarcelo** [comment]
Thanks for reopening this issue. ;) It seems I need to use Dependency Injection along with Castle Windsor to achieve this, but yet I haven't managed to make it work. Here's what I have done:
* Created a new public class MyJsonSerialiser : CacheCow.Server.ISerialiser with the fixed behaviour I want for the Json serialiser.
* In Global.asax.cs, protected void Application_Start():

```
protected void Application_Start()
{
  AreaRegistration.RegisterAllAreas();
  GlobalConfiguration.Configure(WebApiConfig.Register);
  FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
  RouteConfig.RegisterRoutes(RouteTable.Routes);
  BundleConfig.RegisterBundles(BundleTable.Bundles);

  var container = new Castle.Windsor.WindsorContainer();
  ConfigDependencyInjection(container);
  GlobalConfiguration.Configuration.DependencyResolver = new WindsorDependencyResolver(container);
}

static void ConfigDependencyInjection(Castle.Windsor.IWindsorContainer container)
{
  CacheCow.Server.WebApi.CachingRuntime.RegisterDefaultTypes((
    (t1, t2, isTransient) =>
    {
      if (isTransient)
        container.Register(Component.For(t1).ImplementedBy(t2).LifestyleTransient());
      else
        container.Register(Component.For(t1).ImplementedBy(t2).LifestyleSingleton());
    }));

  container.Register(
    Component.For<CacheCow.Server.ISerialiser>().ImplementedBy<hed.hrs_he.com.MyJsonSerialiser>().LifestyleTransient()
  );
}
```
The implementation of WindsorDependencyResolver is a copy of the one in your sample file \samples\CacheCow.Samples.WebApi.WithQueryAndIoc\Program.cs

Still, it does not make the trick and the class being called is your original JsonSerialiser instead of my custom MyJsonSerialiser. Any suggestions? This is my first approach to Castle Windsor (which I found very promising), but I am certainly doing something wrong.

Thanks again for your help and such a good library.

**Comment by aliostad** [comment]
Hi @jagbarcelo 

I just updated the samples project to replace `JsonSerialiser` with your serialiser. Not the `IsDefault()` while registering which replaces previous registrations. When you run the sample, you will see that the new serialiser is being used.

![image](https://user-images.githubusercontent.com/487334/50482133-fd61a200-09dc-11e9-9181-ba3781183de4.png)

**Comment by jagbarcelo** [comment]
Yes! IsDefault() did the trick. Thanks!
