### ISSUE TITLE
Consistency - How to make conditional for put/patch/delete request to make them invalid when they provides diffrent eTag value (Server.Mvc.Core)

### ISSUE THREAD

**Issue by dawcza3** [aliostad/CacheCow#229]
Is there any sample how to work with that situation with Server.Core library ? Currently I installed 2.4.3 version I also tried to use [HttpCache] attribute (like a in sample of CacheCow.Samples.WebApi.WithQueryAndIoc ) but it dosen't detected from namespace. Is there any work around for that or I should use some other attribute to handle put/patch/delete request ?

**Comment by aliostad** [comment]
Hi Dawid,

It is the default behaviour of CacheCow to throw pre-condition failed error when PUT/PATCH/DELETE is presented with a different ETag.

You can already try this with the sample provided look here in the docs:
https://github.com/aliostad/CacheCow#running-samples

**Comment by dawcza3** [comment]
Ok, currently I found what is a main problem. When I send put request without header If-Match, cachecow.server doesn't detect is it not valid request to make put (without place valid if-match). I was expecting that library will protect this kind of action when someone try to edit object without put his version of object (in header of request).

**Comment by aliostad** [comment]
Well, because it is a valid request. If-Match is optional and the client might not have an eTag and might just go ahead with it anyway.

Does this answer you question?

**Comment by dawcza3** [comment]
Yes, thank you for your answers ;)

**Comment by aliostad** [comment]
Thanks for looking into CacheCow!
