### ISSUE TITLE
HttpActionExecutedContext.Response can be null in HttpCacheAttribute

### ISSUE THREAD

**Issue by cam-m** [aliostad/CacheCow#232]
In an `ActionFilterAttribute.OnActionExecuted`, `HttpActionExecutedContext.Response` can be null when a controller has thrown an exception. However in v5.2.6 of `HttpCacheAttribute`, `HttpActionExecutedContext.Response` is not tested for null before use.

Is there known work around to this issue? Perhaps I'm missing something?

ASP Web API 2 v 5.2.6
CacheCow 2.4.3

**Comment by aliostad** [comment]
Thanks for raising this. Looks like a bug.

**Comment by aliostad** [comment]
v 2.4.4 was pushed to nuget. If problem persists, please let me know to re-open the issue.

**Comment by cam-m** [comment]
Thanks so much! Will test today

**Comment by cam-m** [comment]
Confirming this is fixed - thanks so much for turning that around so fast, really appreciate it :)
