### ISSUE TITLE
Controller Add HttpCacheFactoryAttribute Error In .Net Core 3.0

### ISSUE THREAD

**Issue by snowchenlei** [aliostad/CacheCow#234]
Controller Add HttpCacheFactoryAttribute Get Error IN .Net Core 3.0.
"Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead."

**Comment by aliostad** [comment]
Thanks a lot. Will be on t it.

**Comment by aliostad** [comment]
Hi, on further review it might not be related to .NET Core 3.0. Would you be able to send a repro which works against 2.2 but fails on 3.0?

**Comment by snowchenlei** [comment]
Happen In Update .Net Core 2.2 To .Net Core 3.0。
Use Version
![image](https://user-images.githubusercontent.com/26211283/66359754-e52aa480-e9aa-11e9-8638-106ec25370d0.png)
1、Startup：
![image](https://user-images.githubusercontent.com/26211283/66359696-b01e5200-e9aa-11e9-8dfa-5648f59090ce.png)
2、Use：
![image](https://user-images.githubusercontent.com/26211283/66359657-88c78500-e9aa-11e9-803f-9316da6e956f.png)
3、Exception：
    A、Message：Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
    B、Source：Microsoft.AspNetCore.Server.IIS
    C、StackTrace：
![image](https://user-images.githubusercontent.com/26211283/66359636-78afa580-e9aa-11e9-9fc1-1a01ea2a2cc7.png)

**Comment by aliostad** [comment]
Hi, issue is fixed now in version 2.5.0. Can you please check and if you still have a problem I will open the issue again.
