### ISSUE TITLE
Dependency Injection in Core.Mvc

### ISSUE THREAD

**Issue by jagbarcelo** [aliostad/CacheCow#237]
Hi again @aliostad 

This is a question that follows up from our original [https://github.com/aliostad/CacheCow/issues/223].

We are in the process of rewriting our project and moving to .NET Core. Now we have to use CacheCow.Server.Core.Mvc instead of CacheCow.Server.WebApi.

We need to migrate our original WebApi piece of code:

```
private static void ConfigDependencyInjection(Castle.Windsor.IWindsorContainer container)
{
    // ERROR: Mvc Version?
    CacheCow.Server.WebApi.CachingRuntime.RegisterDefaultTypes((
        (t1, t2, isTransient) =>
        {
            if (isTransient)
                container.Register(Component.For(t1).ImplementedBy(t2).LifestyleTransient());
            else
                container.Register(Component.For(t1).ImplementedBy(t2).LifestyleSingleton());
        }));
    container.Register(
        Component.For<CacheCow.Server.ISerialiser>().ImplementedBy<MyNameSpace.MyJsonSerialiser>().IsDefault(),
        Component.For<CacheCow.Server.ICacheabilityValidator>().ImplementedBy<MyNameSpace.MyCacheabilityValidator>().IsDefault()
    );
}
```

But we cannot find any equivalent `CachingRuntime.RegisterDefaultTypes` methods in your `CacheCow.Server.Core.Mvc` namespace.

We are also using the Startup class (instead of Application_Start):

```
public void ConfigureServices(IServiceCollection services)
{
    [...]
    services.AddHttpCachingMvc();

    // Register using a Windsor Castle container
    var container = new Castle.Windsor.WindsorContainer();
    ConfigDependencyInjection(container); // Dependency Injection
    // ERROR: Mvc Version?
    GlobalConfiguration.Configuration.DependencyResolver = new MyNameSpace.WindsorDependencyResolver(container);
    [...]
}
```

But we do not find a way to inject the `DependencyResolver` into the `services` object.

We cannot find a sample of Core.Mvc dependency injection either. The only dependency injection about .NET core mentioned in your documentation is about the ViewModelType, timed ETags, etc. 
However, what we need is a way to register our custom JsonSerialiser and CacheabilityValidator so that the original behaviors can be altered. Can you shed some light on how to achieve this? 

Thanks a lot and great library!

**Comment by aliostad** [comment]
Hi @jagbarcelo have you looked at "Dependency Injection and differentiation of ViewModels" section of this [blog ](https://byterot.blogspot.com/2018/06/cachecowserver-20-using-it-on-aspnetcoremvc-dotnetcore-etag-http-caching-aspnetcore.html)post?

> public virtual void ConfigureServices(IServiceCollection services)
> {
>     ... // register stuff
>     services.AddQueryProviderForViewModelMvc<TestViewModel, TestViewModelQueryProvider>();
>     services.AddQueryProviderForViewModelMvc<IEnumerable<TestViewModel>, TestViewModelCollectionQueryProvider>();
> }
> 
> Other options for register implementations are: AddExtractorForViewModelMvc, AddSeparateDirectiveAndQueryProviderForViewModelMvc or AddDirectiveProviderForViewModelMvc. Some of these extension methods are essentially helpers that combine registration of multiple types.
> 

Essentially, there are various extension methods for registering dependencies depending on your special use case.

You can also find working example in the samples, e.g. [here](https://github.com/aliostad/CacheCow/blob/master/samples/CacheCow.Samples.MvcCore/Startup.cs#L29).

Have a look and let me know if you still need more help.

**Comment by jagbarcelo** [comment]
Thanks for your help.

Turns out that AddQueryProviderForViewModelMvc requires a ViewModel type (not our case).
Finally got it working (almost) with this:

```
public virtual void ConfigureServices(IServiceCollection services)
{
  ...
  services.AddTransient<CacheCow.Server.ISerialiser, MyNameSpace.MyJsonSerialiser>();
  services.AddTransient<CacheCow.Server.ICacheabilityValidator, MyNameSpace.MyCacheabilityValidator>();
  ...
}
```

The problem we are seeing now is that the server seems to be returning right responses (with Cache-Control, ETag,... even x-cachecow-server headers) but the client never makes a conditional get (those with If-None-Match, or If-Modified-Since headers). Because of this, the server is always replying with full new responses (200 Ok) and never a (304 Not modified).

The only special thing we have is that we want the server to reply to authenticated requests as cacheable too. In order to achieve that we have created `MyCacheabilityValidator` based on your original `DefaultCacheabilityValidator` and commented out the lines about authenticated requests:

```
public bool IsCacheable(HttpRequest request)
{
    // none-GET (HEAD is ignored here)
    if (!request.Method.Equals("GET", StringComparison.InvariantCultureIgnoreCase))
        return false;

    // MY CHANGES: We want to be able to cache auth'ed requests too!!!
    //// auth
    //if (request.Headers.Any(x => x.Key.Equals(HttpHeaderNames.Authorization, StringComparison.InvariantCultureIgnoreCase)))
    //    return false;

    // pragma no-cache
    if (request.Headers.Any(x => x.Key.Equals(HttpHeaderNames.Pragma, StringComparison.InvariantCultureIgnoreCase)) &&
        request.Headers[HttpHeaderNames.Pragma].Any(x => x.Contains("no-cache")))
        return false;

    if (request.Headers.Any(x => x.Key.Equals(HttpHeaderNames.CacheControl, StringComparison.InvariantCultureIgnoreCase)) &&
        request.Headers[HttpHeaderNames.CacheControl].Any(x => x.Contains("no-store")))
        return false;

    return true;
}
```

Why is the client never asking requesting a conditional get? Might it be because we need to do Dependency Injection in the client side too in order to override the default behavior of not-caching authenticated queries (despite whatever the server side says)? Previously (when we were using WebApi) we only needed this fix to be applied at the server side.

In the client side we have some middleware as:

```
var pipeline = new CustomDelegatingHandler(LicenseFile)
{
    InnerHandler = new CacheCow.Client.CachingHandler()
    {
        InnerHandler = new HttpClientHandler() { AutomaticDecompression = DecompressionMethods.All }
    }
};
MyHttpClient = new HttpClient(pipeline);
```

The first CustomDelegatingHandler is in charge of inserting the Authorization headers in the requests, based on the information provided in the LicenseFile. The second one is your CacheCow.Client and the third one is for using compression (GZip, Deflate or Brotli).

Previously, in our WebApi version (which worked perfectly), we had this in the client side (it seems equivalent to me, although a bit less visual):

```
var compressionHandler = new HttpClientHandler();
if (compressionHandler.SupportsAutomaticDecompression) compressionHandler.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;
var cachingHandler = new CacheCow.Client.CachingHandler() { InnerHandler = compressionHandler };
MyHttpClient = HttpClientFactory.Create(cachingHandler, new DelegatingHandler[] { new CustomDelegatingHandler(LicenseFile) });
```

A sample request / response of the new version (.NET core) which never makes conditional requests.

```
GET https://localhost:44370/api/v1.0/user/1ca7c112-dde2-e571-e081-90155d0b0711/project/paging?useDateCreated=True&year=2019&month=9&pageSize=25 HTTP/1.1
Host: localhost:44370
Accept: application/json
Accept-Language: es-ES
Cache-Control: max-age=86400, private
User-Agent: MYAPP-DEBUG/2.1.1.0
Authorization: amx 23e07635-783f-4dc2-a6a4-1cbc4036fb21:86F1-ACCD-8331-7E90-A9F8-CC3F-2A8C-09A2:KMaQVNXi8pHzV8UnRQ8bKOnoTrFf22ZfwDTysycB4b0=:c3e4ae5c29604f7da0ddfe73bca5e232:1571384223
Accept-Encoding: gzip, deflate, br


HTTP/1.1 200 OK
Cache-Control: public, must-revalidate, max-age=86400
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Content-Encoding: br
ETag: "a4ayc/80/OGda4BO/1o/V0etpOqiLx1JwB5S3beHW0s="
Vary: Accept,Accept-Encoding
Server: Microsoft-IIS/10.0
x-cachecow-server: validation-applied=False;validation-matched=False;short-circuited=False;query-made=False
X-Powered-By: ASP.NET
Date: Fri, 18 Oct 2019 07:37:02 GMT
[Body Removed]
```

Any ideas about why the client seems not to be using CacheCow.Client at all? Thanks again for your help and time.

**Comment by aliostad** [comment]
This is a different problem - you are now saying the server behaves correctly but the client does not, right? In that case please open a new issue and I will be looking into - which relates to CacheCow.Client.

**Comment by jagbarcelo** [comment]
Ok. I will be copying/pasting most of the former message though ;)
