### ISSUE TITLE
Support StackExchange.Redis v2

### ISSUE THREAD

**Issue by evo-terren** [aliostad/CacheCow#239]
StackExchange.Redis v2+ require .net framework 4.6.1+ therefore CacheCow.Client.RedisCacheStore locks you into v1 of the Redis library. Please add support for v2+.

**Comment by aliostad** [comment]
Can you please confirm I can close it?

**Comment by evo-terren** [comment]
Oh whoops. Yes I'll do that now. Thanks again!
