### ISSUE TITLE
Remove x-cachecow-server header

### ISSUE THREAD

**Issue by totidev** [aliostad/CacheCow#242]
The documentation says that 'x-cachecow-server' diagnostic headers are included. How can I disable these headers from appearing?

**Comment by aliostad** [comment]
At this point, no. Would you need the option? I can add the option.

**Comment by totidev** [comment]
It would be nice to opt into the headers in a production environment/release builds. During development, it is useful for me to see the diagnostic header - but I would almost never see these in production.

**Comment by aliostad** [comment]
Sure I think makes sense to control this behaviour through configuration. One problem of course is the divergence and differences of configuration in the old and the new world - but I have dealt with similar so will implement in the next couple of days.

**Comment by aliostad** [comment]
With version 2.6.0 (just released) you will be able to turn off sending the header. You just need to, in your configuration, set `do_not_emit_cachecow_header` to true. Also there are options for the client, setting a property to `true` on the `CachingHandler`.

Can you please confirm this solves the issue?

**Comment by totidev** [comment]
Hi, I can confirm that this does work.
However, do you think it is possible to support a format similar to the following:

            services.AddHttpCachingMvc(config =>
            {
                config.DoNotEmitHeader = true
            });
If not, it still works perfectly.

**Comment by aliostad** [comment]
Yeah, that is the convention, I should have followed... sure will do it. Thanks for the hint.

**Comment by aliostad** [comment]
This is done now and available in 2.6.1.
