### ISSUE TITLE
Set Cache Expiration at runtime

### ISSUE THREAD

**Issue by circleupx** [aliostad/CacheCow#245]
_Opening this question as an issue as suggest in_ https://github.com/aliostad/CacheCow/issues/244#issuecomment-575598860

Do you have any advice on my other question? Is this possible within CacheCow? 

> Is it possible to set the cache expiration at runtime? Like I would omit the cache expiration from HttpCacheFactory then at runtime calculate the cache expiration base on the state of the resource.

I have a REST API that may return multiple resource types base on the client request. 

I would to set the expiration base the resource types within the HTTP response. For example, assume that an API has two resources, car and passenger and I decorate the controller like so,

```C#
public class CarController : Controller
{
    [HttpGet]
    [HttpCacheFactory(300, ViewModelType = typeof(Car))]
    public IActionResult Get(int id)
    {
        ... // implementation
    }
}

public class PassengerController : Controller
{
    [HttpGet]
    [HttpCacheFactory(60, ViewModelType = typeof(Passenger))]
    public IActionResult Get(int id)
    {
        ... // implementation
    }
}
```

The car resource has an expiration of 5 minutes, car information doesn't change that much. Passengers on the other hand is more volatile so I want to keep the cache time low, 1 minute. 

Now, a client makes an HTTP request like so,

https://api.example.com/cars

With the current CacheCow configuration defined above, the server would response with Cache-Control: public, max-age=500.

Cool so far, everything works are expected and the correct cache expiration is set.

Now, assume that the car resource has a one to many relationship to passengers, and through ORM frameworks like EF CORE we can include then on our query should the client ask for resource.

Possible client request may look like this,

https://api.example.com/cars?include=passengers.

With the current CacheCow configuration defined above, the server would response with Cache-Control: public, max-age=500, but in this case I actually want to set the cache expiration to 1 minute because of the inclusion of passengers. 

Thanks!

**Comment by aliostad** [comment]
Thanks for separating the question. As discussed:

`ICacheDirectiveProvider` interface and `GetCacheControl` method is responsible for providing the CacheControlHeader. It mainly operates on configuredExpiry but you can override it. Here is the implementation from `DefaultCacheDirectiveProvider`:

``` csharp
#if NET452
        public CacheControlHeaderValue GetCacheControl(HttpActionExecutedContext context, TimeSpan? configuredExpiry)
#else
        public CacheControlHeaderValue GetCacheControl(HttpContext context, TimeSpan? configuredExpiry)
#endif
        {
            switch (configuredExpiry)
            {
                case TimeSpan t when t == TimeSpan.Zero:
                    return new CacheControlHeaderValue() { MaxAge = TimeSpan.Zero, Private = true, MustRevalidate = true };
                case TimeSpan t:
                    return new CacheControlHeaderValue() { MaxAge = t, Public = true, MustRevalidate = true };
                default:
                    return new CacheControlHeaderValue() { NoCache = true, NoStore = true };
            }
        }
    }

```

So you need to create your own implementation which looks at the query string. Context parameter contains all information you need to make a decision.

You need to register your type. If you use the Generic interface means you can override for only when it returns a specific type which targets you method.

I could create an example but I cannot promise when exactly I will be able to.
