### ISSUE TITLE
Latest version references invalid Microsoft.Extensions.Configuration.Binder

### ISSUE THREAD

**Issue by totidev** [aliostad/CacheCow#250]
Since updating to 2.7.0, Nuget reports the following error:

_CacheCow.Server.Core.Mvc 2.7.0 depends on Microsoft.Extensions.Configuration.Binder (>= 2.0.3) but Microsoft.Extensions.Configuration.Binder 2.0.3 was not found. An approximate best match of Microsoft.Extensions.Configuration.Binder 2.1.0 was resolved._

Looking at Nuget for Microsoft.Extensions.Configurations.Binder, suggests that there is no version 2.0.3: https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Binder

**Comment by aliostad** [comment]
Thanks for raising this. I will fix it now.

**Comment by aliostad** [comment]
v2.7.1 released.
