### ISSUE TITLE
CacheCow.Server.DefaultCacheDirectiveProvider registration problems in v2.7.4

### ISSUE THREAD

**Issue by memeny** [aliostad/CacheCow#254]
I have tried v2.7.4 and am now having problems with my Autofac registration code, using the "standard" method to register CacheCow's internal implementations:

            CachingRuntime.RegisterDefaultTypes(
                (t1, t2, isTransient) => {
                    if (isTransient)
                        builder.RegisterType(t2).As(t1);
                    else
                        builder.RegisterType(t2).As(t1).SingleInstance();
                });

The reported exception is:

"System.ArgumentException: 'The type 'CacheCow.Server.DefaultCacheDirectiveProvider`1[TViewModel]' is not assignable to service 'CacheCow.Server.ICacheDirectiveProvider`1'.'"

**Comment by aliostad** [comment]
Hi, the issue is that in AutoFac, registering a type is different from registering a generic type and you need to use `RegisterGeneric`.

As such, just add a condition:
``` csharp
if (t1.IsGeneric)
      builder.RegisterGeneric(t2).As(t1);
else
     ....
```

So it is just the way Autofac works.

Does this help?

**Comment by memeny** [comment]
Thanks Ali, that’s sorted it.

Presumably you have added some generic types to v2.7.4 – great that I’ve been able to upgrade now.

Thanks again for your efforts with this library – really useful.

**Comment by aliostad** [comment]
Awesome! Thanks for using CacheCow.
