### ISSUE TITLE
no-cache problem in Net Core application

### ISSUE THREAD

**Issue by balsamiqLuca** [aliostad/CacheCow#255]
Hi, 

I need to use caching with Etag and I noticed that the check on the no-cache header is performed after the check on the Expires header, so it always returns not-cacheable.
When the strategy is no-cache, it should not be required that the Expires header is set, so maybe the check on the no-cache should go before the check on the Expires header:

https://github.com/aliostad/CacheCow/blob/b2b2e2b988d079e5e9305d7ac4d1f7c1908c6b7f/src/CacheCow.Client/CachingHandler.cs#L94

This is an example of a response that does not get cached:
```
HTTP/1.1 200 OK
Date: Mon, 24 Aug 2020 09:02:57 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 159715
Connection: keep-alive
Set-Cookie: AWSALB=MfAWemuHVk7WV4gahD7pZR4lRzE1cqbjiNmFtMiUK00d0c62aLuTYU2VmvKUsp6+aJ4+fmucz7rRAhj+fDPc9lmPcvWRfF+8xYjzJoStKOu5cpBZr/H60yCYm936; Expires=Mon, 31 Aug 2020 09:02:57 GMT; Path=/
Set-Cookie: AWSALBCORS=MfAWemuHVk7WV4gahD7pZR4lRzE1cqbjiNmFtMiUK00d0c62aLuTYU2VmvKUsp6+aJ4+fmucz7rRAhj+fDPc9lmPcvWRfF+8xYjzJoStKOu5cpBZr/H60yCYm936; Expires=Mon, 31 Aug 2020 09:02:57 GMT; Path=/; SameSite=None; Secure
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: x-balsamiq-archive-revision
Strict-Transport-Security: max-age=31536000; includeSubDomains
ETag: "19eb1c071d7e8166c785780f123c775d05aaf2cb"
X-Balsamiq-Archive-Revision: 770
Cache-Control: no-cache, private, must-revalidate
Vary: Accept-Encoding
````

**Comment by aliostad** [comment]
Hi sorry, was on holiday, just back. Will have a look.

**Comment by aliostad** [comment]
It does not say it cannot be cached, it says it must be re-validated. Normally these would be cached but they would still be validated every time. With no-cache (and especially must-revalidate), expiry does not matter. So what is the CacheCow header you get back?

**Comment by balsamiqLuca** [comment]
Hi, thanks for the answer!
The CacheCow headers I get back say: "not-cacheable=true;did-not-exist=true", due to the fact (I think) that in the CachingHandler ResponseValidator function it's checking the Expires before the "no-cache":
         ```
       if (response.Headers.CacheControl.MaxAge == null &&
                    response.Headers.CacheControl.SharedMaxAge == null &&
                    response.Content.Headers.Expires == null)
                    return ResponseValidationResult.NotCacheable;

                if (response.Headers.CacheControl.NoCache)
                    return ResponseValidationResult.MustRevalidate;
```

**Comment by aliostad** [comment]
I think the "NotCacheable" is misleading. Can you check on subsequent requests whether it validates it?

**Comment by balsamiqLuca** [comment]
It keeps saying: not-cacheable=true,did-not-exist=true

**Comment by aliostad** [comment]
Well, if a response has `Set-Cookie` header, it is not cacheable. I was not sure if I had implemented it but just double checked and I have. If you remove `Set-Cookie` headers it should work.

https://github.com/aliostad/CacheCow/blob/master/src/CacheCow.Server/Cacheability/DefaultCacheabilityValidator.cs#L89

Let me know if you need have more questions, otherwise will be closing the issue.

**Comment by balsamiqLuca** [comment]
Hi, 
we removed the Set-Cookie from the response but it still says not-cacheable. 
This is the new response:
```
HTTP/1.1 200 OK
Date: Tue, 25 Aug 2020 08:47:29 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 387855
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: x-balsamiq-archive-revision
Strict-Transport-Security: max-age=31536000; includeSubDomains
ETag: "b4fbbd330bf15d643e06eafd6e4bf570d8d899d3"
X-Balsamiq-Archive-Revision: 770
Cache-Control: no-cache, private, must-revalidate
Vary: Accept-Encoding
```

**Comment by aliostad** [comment]
OK, does your response have a content? If it does not, currently cacheCow does not cache it - not really a point.

**Comment by aliostad** [comment]
OK, the issue obviously is that since it does not know how long it should cache it, it deems it as non-cacheable. This is an edge case and I believe a cacheable resource should have an age or expires header.

Is it not possible to have it in your case?

**Comment by balsamiqLuca** [comment]
Hi! 
Ok, we'll override the function as you said. Thanks for your support!

**Comment by aliostad** [comment]
Anytime! Thanks for using CacheCow.
