### ISSUE TITLE
Source code cannot be mapped for released nuget packages

### ISSUE THREAD

**Issue by patspaeth** [aliostad/CacheCow#282]
We as a company need to do license clearing and so we need to know what source code matches a particular released nuget version. Is it possible to at least tag the source code with the released version?

**Comment by aliostad** [comment]
Hi,

Yes tagging is a good practice. I can tag it from now on. Would that be fine for you?

**Comment by patspaeth** [comment]
Please tag for the latest release 2.11.0 if suitable.

**Comment by patspaeth** [comment]
then it is fine for me

**Comment by aliostad** [comment]
This is done now `v2.11.1`. I actually had been tagging until version 2.7.1 but somehow I have forgotten to do that.
