### ISSUE TITLE
Possibility to update Microsoft.AspNet.WebApi.Client to 5.2.9

### ISSUE THREAD

**Issue by czthiele** [aliostad/CacheCow#283]
Hello @aliostad, thank you for the good work on CacheCow.

Since you have already updated Newtonsoft, do you see the possibility to also update Microsoft.AspNet.WebApi.Client to stay up to date? Version 5.2.5 is already 4 years old and they released some fix versions this year. What do you think?

Best regards
Alex

**Comment by aliostad** [comment]
The version you are running with can be higher. This is the minimum version. But I will have a look.

**Comment by aliostad** [comment]
Done. Check `v2.11.2`.
