### ISSUE TITLE
Memory leak in CacheCow.Client.CachingHandler

### ISSUE THREAD

**Issue by lostdev** [aliostad/CacheCow#47]
Hi,

In the constructor of the client's `CachingHandler` the `VaryHeaderStore` cache is initialized with a new instance of [`InMemoryVaryHeaderStore`](https://github.com/lostdev/CacheCow/blob/8d3cb1d0a39f0f435620a5c1ee4c524ead1730ff/src/CacheCow.Client/CachingHandler.cs#L42).

The `InMemoryVaryHeaderStore` class initializes a new `MemoryCache` object internally which implements  `IDisposable` (and is never disposed). This very quickly leads to `OutOfMemoryExceptions` when a new HTTP client is initialized per request.

**Comment by xunilrj** [comment]
aliostad
> However, we are not supposed to create HttpClient or CachingHandler over and over again - use a share HttpClient for all your calls.  It is completely safe to reuse it.

lostdev 
>We've been instantiating the client per-request in our web application to simplify authentication and other per-user settings (such as passing around cookies).

I have the same scenario here. Although it is safe to have one static/singleton HttpClient, sometimes is better to have more than one instance. Multi tenant scenarios with one HttpClient preconfigured for each client, to give just one example.

I have made a simple modification that one additional constructor accepts both ICacheStore and IVaryHeaderStore by injection and the CachingHandler only disposes those dependencies that were injected. When they are created by the CachingHandler they are disposes as before.

Are you interested in the Pull Request to see if you consider the modification useful?

**Comment by aliostad** [comment]
Hi,

This has been fixed and if you dispose the HttpClient, it will dispose the handlers as well.
https://github.com/aliostad/CacheCow/blob/master/src/CacheCow.Client/CachingHandler.cs#L508

**Comment by xunilrj** [comment]
Yes, but, for example, suppose I create and dispose the HttpClient and its pipeline in every request that my server accepts. Now I have two problems:

First, the CachingHandler will recreate the InMemoryVaryHeader, that will recreate the MemoryCache in every request. It is not an absurdly expensive class, but it is much more expensive than a normal class (1).

Second, when the CachingHandler is created with an injected cache store, the store is disposed with the Cachinghandler.

https://github.com/aliostad/CacheCow/blob/master/src/CacheCow.Client/CachingHandler.cs#L509

What I am trying to say is that the DI pattern does not make clear if an injection is the same as ownership transference. Is this case, the CachingHandler is assuming that it owns the CacheStore, so when it suffer a Dispose, it disposes the CacheStore. And in a scenario where the injected CacheStore is shared, this cause problems.

(1) In a loop I create 1000 MemoryCache in 200ms and create 1000 dummy objects in 0ms.

**Comment by IDisposable** [comment]
Addressing only the second issue. If you want to not transfer ownership to CacheCow, the logical thing to do is to inject a wrapper object that either:

A) Doesn't implement IDisposable
B) Implements IDisposable but does not dispose the wrapped cache handler.

When you take one life-cycle management, you get to make the rules :)

**Comment by aliostad** [comment]
@IDisposable @xunilrj 
Hi, you are correct. First off, the fact that `CachingHandler` disposes the `ICacheStore` - when it is passed to it - is wrong. This will be fixed.
Second, I can accommodate the change of adding the new constructor for passing VaryHeaderStore. 

This will be done this weekend.

**Comment by xunilrj** [comment]
Thanks, I will be more than happy to test and report back to you the result! :smile:

**Comment by aliostad** [comment]
Please let me know if this is not fixed
