### ISSUE TITLE
Sign NuGet assemblies with strong name

### ISSUE THREAD

**Issue by seniorquico** [aliostad/CacheCow#66]
Signing the assemblies would make it possible to reference CacheCow assemblies from other components that have a strong name. Thanks for your time and such a great project!

**Comment by carstenschuette** [comment]
I come back to this old (still unresolved) issue, NuGet packages are still weak named. Is there any reason why CacheCow assemblies cannot have a strong name?

**Comment by aliostad** [comment]
OK, I am working on it.
@carstenschuette only handful of projects can compile since they do depend on unsigned assemblies.
I am releasing them, can you please let me know which ones are needed by you?

**Comment by aliostad** [comment]
These are released now. e.g. https://www.nuget.org/packages/CacheCow.Common.sn/1.1.1
