### ISSUE TITLE
In SqlServerEntityTagStore the first call returns weak key and the next are strong

### ISSUE THREAD

**Issue by gdoron** [aliostad/CacheCow#93]
I'm not doing anything special, this is my only direct usage of CacheCow in my WebApi-OData project:
	
```C#
var connectionString = ConfigurationManager.ConnectionStrings["Context"].ConnectionString;
var eTagStore = new SqlServerEntityTagStore(connectionString);
var cacheHandler = new CachingHandler(config, eTagStore);
```

First call:
ETag: W/"95411d3e14ec45f49556fd4bdeed1821"
Second call: 
ETag: "95411d3e14ec45f49556fd4bdeed1821"

**Comment by aliostad** [comment]
Best to avoid SQL Server storage.
